---
settings:
  name: ONTAP tools for VMware vSphere 9.11
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: ONTAP Tools für VMware vSphere
    url: "/ontap-tools-vmware-vsphere"
    version-number: '9.11'
  - name: ONTAP Tools für VMware vSphere
    url: "/ontap-tools-vmware-vsphere-910"
    version-number: '9.10'
  - name: ONTAP Tools für VMware vSphere
    url: "/ontap-tools-vmware-vsphere-98"
    version-number: '9.8'
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: ONTAP-Tools für VMware vSphere 9.11 - Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/release_notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Versionshinweise
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2883436
    - title: Erfahren Sie mehr über ONTAP Tools für VMware vSphere
      url: "/concepts/concept_virtual_storage_console_overview.html"
    - title: ONTAP-Tools Schnellstartanleitung
      url: "/qsg.html"
    - title: Implementierung von ONTAP Tools
      url: "/deploy/task_deploy_ontap_tools.html"
    - title: Upgrade von ONTAP-Tools
      url: "/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html"
  - title: Verwenden Sie ONTAP-Tools
    links:
    - title: Bereitstellung herkömmlicher Datastores
      url: "/configure/task_provision_datastores.html"
    - title: Bereitstellung von VVols Datastores
      url: "/configure/task_provision_vvols_datastores.html"
    - title: Konfigurieren Sie die rollenbasierte Zugriffssteuerung
      url: "/concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html"
    - title: Konfigurieren Sie die Remote-Diagnose
      url: "/manage/task_configure_vasa_provider_to_use_ssh_for_remote_diag_access.html"
    - title: Konfigurieren Sie Hochverfügbarkeit
      url: "/concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html"
  - title: Sicherung und Management von Datenspeichern
    links:
    - title: Sichern Sie Ihre Datenspeicher
      url: "/protect/task_enable_storage_replication_adapter.html"
    - title: Sicherung von Virtual Machines
      url: "/protect/concept_configure_replication_for_vvols_datastore.html"
    - title: Überwachen Sie herkömmliche Datenspeicher und Virtual Machines
      url: "/manage/task_monitor_datastores_using_the_traditional_dashboard.html"
    - title: Überwachen Sie VVols Datastores und Virtual Machines
      url: "/manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html"
  - title: Mehr Ressourcen
    links:
    - title: Dokumentation für frühere Versionen von ONTAP-Tools für VMware
      url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=63792
    - title: NetApp Knowledge Base – ONTAP Tools
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider
    - title: NetApp Import Utility – Video
      url: https://www.youtube.com/watch?v=CEQmIEzNVfA
    - title: NetApp Community – ONTAP Tools
      url: https://community.netapp.com/t5/VMware-Solutions-Discussions/bd-p/vmware-solutions-discussions
