---
sidebar: sidebar 
permalink: qsg.html 
keywords: QSG, ONTAP tools for VMware vSphere, Quick start guide, Installing 
summary: Enthält Anweisungen zur Bereitstellung und Initialisierung von ONTAP Tools für VMware vSphere. 
---
= ONTAP-Tools für VMware vSphere Quick Start
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die ONTAP Tools für VMware vSphere sind ein einzelnes vCenter Server Plug-in, das ONTAP Tools, VASA Provider und SRA-Erweiterungen (Storage Replication Adapter) umfasst. ONTAP Tools werden für alle ONTAP vSphere Umgebungen empfohlen, da ESXi Host-Einstellungen konfiguriert und ONTAP Storage mithilfe von Best Practices bereitgestellt wird. VASA Provider ist für die Unterstützung von virtuellen Volumes (VVols) erforderlich und SRA arbeitet zusammen mit VMware Site Recovery Manager.



== Installation wird vorbereitet

Sie stellen das Plug-in als virtuelle Appliance bereit, wodurch Sie weniger Aufwand bei der Installation und Registrierung jedes einzelnen Produkts beim vCenter Server benötigen.



=== Implementierungsanforderungen zu erfüllen

ONTAP-Tools können mit einer virtuellen VMware vCenter Server-Appliance (vCSA) verwendet werden. Sie müssen die ONTAP-Tools auf einer unterstützten vSphere bereitstellen, die auch das ESXi-System umfasst.

Die Mindestanforderungen für Speicherplatz und Host bezüglich Größenbemessung sind:

[cols="25,75"]
|===
| *System* | *Mindestanforderungen* 


| Platzbedarf | 2.1 GB bei Thin Provisioning-Installationen, 54.0 GB bei Thick Provisioning-Installationen 


| Host-Dimensionierung | Empfohlener Speicher: 12 GB, Empfohlene CPUs: 2 
|===
Sie sollten die folgenden Lizenzen kennen:

[cols="25,75"]
|===
| *Lizenz* | *Beschreibung* 


| SnapMirror | (Optional) erforderlich zur Durchführung von Failover-Vorgängen für SRA und VASA Provider bei Nutzung der VVols Replizierung. 


| FlexClone | (Optional) erforderlich zur Durchführung von Test-Failover-Vorgängen für SRA und für VVols des VASA-Providers. 
|===
ONTAP-Tools verwenden die folgenden bidirektionalen TCP-Standardports:

|===


| *Zusätzliche Anforderungen* | *Beschreibung Spalte* 


 a| 
9083
 a| 
Bei Aktivierung verwenden sowohl VASA Provider als auch Storage Replication Adapter (SRA) diesen Port zur Kommunikation mit dem vCenter Server. Dieser Port wird auch zum Abrufen der TCP/IP-Einstellungen benötigt. Dieser Port dient zum Herunterladen des VP-Support-Pakets, zum Zugriff auf die Web-CLI-Benutzeroberfläche und zur Steuerung der Pfadkommunikation von VMware zu VP.



 a| 
443
 a| 
Je nach Konfiguration Ihrer Anmeldedaten achten VMware vCenter Server und die Speichersysteme auf die sichere Kommunikation auf diesem Port. Der Port wird in der Client-Server-Kommunikationsarchitektur verwendet. Der Port 443 ist standardmäßig für sichere Verbindungen aktiviert. Der Client, der beliebige Automatisierungs-Client sein kann, der REST API verwendet, initiiert die Verbindung zum Server und den Datenaustausch mit den Endpunkten.



 a| 
8143
 a| 
Die ONTAP-Tools sorgen für eine sichere Kommunikation über diesen Port. Der Port wird in der Client-Server-Kommunikationsarchitektur verwendet. Der Client, der beliebige Automatisierungs-Client sein kann, der REST API verwendet, initiiert die Verbindung zum Server und den Datenaustausch mit den Endpunkten. Dieser Port ist für ONTAP-Tools-Dienste und für den Export von Serverprotokollen der ONTAP-Tools aktiviert. Die Seite register.html wird auf diesem Port gehostet. Der REST-Schwagger ist an diesem Port freigelegt.



 a| 
8443
 a| 
Dieser Port wird für den Remote-Plugin-Dienst verwendet.

|===
Minimale Storage- und Applikationsanforderungen:

|===
| *Speicher, Host und Anwendungen* | *Versionsvoraussetzungen* 


| ONTAP | ONTAP 9.7, 9.8P1 oder höher 


| VMware vSphere, vCenter Server, ESXi Hosts, Site Recovery Manager (SRM), Plug-in-Applikationen und Datenbanken, Spalte 1 | Siehe https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Interoperabilitäts-Matrix-Tool"^] 
|===


=== Anforderungen für ONTAP-Tools

* Konfigurieren und richten Sie Ihre vCenter Server-Umgebung ein.
* Laden Sie die .ova-Datei herunter.
* Die Anmeldeinformationen für Ihre vCenter Server-Instanz.
* Löschen Sie den Browser-Cache, um Probleme mit dem Browser-Cache während der Bereitstellung der ONTAP-Tools zu vermeiden.
* Konfigurieren Sie das Standard-Gateway, das von der virtuellen Appliance verwendet werden soll, um auf ICMP-Pings zu reagieren.
* Ein gültiger DNS-Hostname für die virtuelle Appliance.




=== Optionale Anforderungen an SRA

Wenn Sie die virtuelle Appliance zur Verwendung mit VMware Site Recovery Manager implementieren, müssen Sie: * Heruntergeladen haben `.tar.gz` Datei für SRA, wenn Sie die SRM-Appliance nutzen.



== Einsatz von ONTAP Tools

.Schritte
. Download `.zip` Datei, die Binärdateien und signierte Zertifikate vom enthält https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support Website"^] Auf einem vSphere Client System zur Bereitstellung der ONTAP Tools.
. Extrahieren Sie die `.zip` Datei und implementieren Sie die `.ova` Datei:
+
Sie müssen die bereitstellen `.ova` Datei auf den Quell- und Zielstandorten, wenn Sie SRA implementieren.

. Melden Sie sich beim vSphere Web Client an, wählen Sie *Home* > *Host und Cluster*.
. Klicken Sie mit der rechten Maustaste auf das gewünschte Rechenzentrum und klicken Sie dann auf *OVF-Vorlage bereitstellen*.
+
Wenn Sie vCenter7.0u3e und neuere Versionen verwenden, führen Sie die folgenden Aktionen durch, andernfalls fahren Sie mit Schritt 5 fort. Dies ist ein optionaler Schritt, um zu überprüfen, ob die OVA-Binärintegrität nicht manipuliert wird.

+
** Laden Sie die Datei _OTV_INTER_ROOT_CERT_CHAIN.pem_ von der NetApp Support-Website herunter.
** Navigieren Sie zu *vcenter* > *Administration* > *Certificate Management*.
** Klicken Sie auf die Option *vertrauenswürdiges Stammzertifikat hinzufügen*.
** Klicken Sie auf *Browse* und geben Sie den Pfad für die Datei _OTV_INTER_ROOT_CERT_CHAIN.pem_ an.
** Klicken Sie Auf *Hinzufügen*.
+

NOTE: Die Meldung Code Signing anvertrauen - OVCS2 (vertrauenswürdiges Zertifikat) bestätigt die Integrität der heruntergeladenen OVA-Datei. Wenn die Meldung Code Signing anvertrauen - OVCS2 (ungültiges Zertifikat) angezeigt wird, aktualisieren Sie den VMware vCenter Server auf die Version 7.0U3E oder höher.



. Sie können entweder die URL für die .ova-Datei eingeben oder in den Ordner navigieren, in dem die .ova-Datei gespeichert ist, und dann auf *Next* klicken.
. Geben Sie die erforderlichen Details ein, um die Implementierung abzuschließen.



NOTE: (Optional) Wenn Sie Container erstellen möchten, ohne sich bei vCenter Server zu registrieren, aktivieren Sie im Abschnitt vCenter konfigurieren oder VCF aktivieren das Kontrollkästchen VMware Cloud Foundation (VCF) aktivieren.

Sie können den Fortschritt der Bereitstellung über die Registerkarte *Tasks* anzeigen und warten, bis die Bereitstellung abgeschlossen ist.

Im Rahmen der Implementierung werden Prüfsummenverifizierungen durchgeführt. Wenn die Bereitstellung fehlschlägt, gehen Sie wie folgt vor:

. Überprüfen Sie vpserver/logs/checksum.log. Wenn dort die Meldung „Prüfsummenverifikation fehlgeschlagen“ steht, können Sie die fehlgeschlagene JAR-Verifizierung im gleichen Protokoll sehen.
+
Die Protokolldatei enthält die Ausführung von _sha256sum -c /opt/netapp/vpserver/conf/Checksummen_.

. Überprüfen Sie vscserver/log/checksum.log. Wenn dort die Meldung „Prüfsummenverifikation fehlgeschlagen“ steht, können Sie die fehlgeschlagene JAR-Verifizierung im gleichen Protokoll sehen.
+
Die Protokolldatei enthält die Ausführung von _sha256sum -c /opt/netapp/vscerver/etc/Prüfsummen_.





=== SRA auf SRM implementieren

SRA kann entweder auf Windows SRM Server oder auf 8.2 SRM Appliance implementiert werden.



==== Hochladen und Konfigurieren von SRA auf der SRM-Appliance

.Schritte
. Laden Sie die herunter `.tar.gz` Datei von https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support Website"^].
. Klicken Sie auf dem Bildschirm der SRM-Appliance auf *Storage Replication Adapter* > *Neuer Adapter*.
. Laden Sie die hoch `.tar.gz` Datei zu SRM.
. Überprüfen Sie die Adapter erneut, ob die Details auf der Seite SRM Storage Replication Adapter aktualisiert werden.
. Melden Sie sich mit dem Administratorkonto an der SRM-Appliance mithilfe des Putty an.
. Zum Root-Benutzer wechseln: `su root`
. Geben Sie im Protokollverzeichnis den Befehl ein, um die vom SRA-Docker-Andocker verwendete Docker-ID zu erhalten: `docker ps -l`
. Melden Sie sich bei der Container-ID an: `docker exec -it -u srm <container id> sh`
. Konfigurieren Sie SRM mit der IP-Adresse und dem Passwort der ONTAP Tools: `perl command.pl -I <otv-IP> administrator <otv-password>`. Sie benötigen ein einziges Angebot um den Passwortwert herum.
Eine Erfolgsmeldung, die bestätigt, dass die Speicher-Anmeldedaten gespeichert werden, wird angezeigt. SRA kann mit dem SRA-Server unter Verwendung der angegebenen IP-Adresse, des Ports und der Anmeldeinformationen kommunizieren.




==== SRA-Anmeldedaten werden aktualisiert

.Schritte
. Löschen Sie den Inhalt des Verzeichnisses /srm/sra/conf mit:
+
.. `cd /srm/sra/conf`
.. `rm -rf *`


. Führen Sie den Perl-Befehl aus, um SRA mit den neuen Zugangsdaten zu konfigurieren:
+
.. `cd /srm/sra/`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`. Sie benötigen ein einziges Angebot um den Passwortwert herum.
+
Eine Erfolgsmeldung, die bestätigt, dass die Speicher-Anmeldedaten gespeichert werden, wird angezeigt. SRA kann mit dem SRA-Server unter Verwendung der angegebenen IP-Adresse, des Ports und der Anmeldeinformationen kommunizieren.







==== Aktivieren von VASA Provider und SRA

.Schritte
. Melden Sie sich beim vSphere-Web-Client mit der vCenter-IP an, die während der Bereitstellung der OVA-ONTAP-Tools bereitgestellt wurde.
. Klicken Sie auf der Shortcuts-Seite unter Plug-ins auf *NetApp ONTAP Tools*.
. Im linken Bereich der ONTAP-Tools, *Einstellungen > Verwaltungseinstellungen > Funktionen verwalten*, und aktivieren Sie die erforderlichen Funktionen.
+

NOTE: VASA Provider ist standardmäßig aktiviert. Wenn Sie die Replizierungsfunktion für VVols-Datastores verwenden möchten, aktivieren Sie die Kippschaltfläche zum Aktivieren der VVols-Replizierung.

. Geben Sie die IP-Adresse der ONTAP-Tools und das Administratorpasswort ein, und klicken Sie dann auf *Anwenden*.

