---
permalink: deploy/concept_configure_your_storage_system_environment.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools für VMware vSphere bietet einen einzigen Mechanismus, um Storage-Systeme zu erkennen und die Storage-Anmeldedaten festzulegen. Die Zugangsdaten liefern die ONTAP Berechtigungen, die erforderlich sind, um Benutzern von ONTAP Tools die Ausführung von Aufgaben mithilfe der Storage-Systeme zu ermöglichen. 
---
= Konfigurieren Sie die ONTAP Tools für das VMware vSphere Storage-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools für VMware vSphere bietet einen einzigen Mechanismus zur Erkennung von Storage-Systemen und zur Festlegung von Storage-Zugangsdaten. Die Zugangsdaten liefern die ONTAP Berechtigungen, die erforderlich sind, um Benutzern von ONTAP Tools die Ausführung von Aufgaben mithilfe der Storage-Systeme zu ermöglichen.

Bevor ONTAP-Tools die Storage-Ressourcen anzeigen und verwalten können, müssen ONTAP-Tools die Storage-Systeme erkennen. Im Rahmen des Erkennungsvorgangs müssen Sie die ONTAP Zugangsdaten für Ihre Storage-Systeme angeben. Hierbei handelt es sich um die Berechtigungen (oder Rollen), die mit dem Benutzernamen und dem Kennwort-Paar verknüpft sind, das jedem Speichersystem zugewiesen ist. Diese Benutzername und Passwort-Paare verwenden die rollenbasierte Zugriffssteuerung (Role-Based Access Control, RBAC) von ONTAP und müssen aus ONTAP heraus eingerichtet werden. Sie können diese Anmeldeinformationen nicht in ONTAP Tools ändern. ONTAP RBAC-Rollen können Sie mit ONTAP System Manager definieren.


NOTE: Wenn Sie sich als Administrator anmelden, verfügen Sie automatisch über alle Berechtigungen für dieses Speichersystem.

Wenn Sie ONTAP Tools ein Storage-System hinzufügen, müssen Sie eine IP-Adresse für das Storage-System sowie den Benutzernamen und das Passwort-Paar angeben, die dem System zugeordnet sind. Sie können Standardanmeldeinformationen einrichten, die ONTAP-Tools während der Erkennung des Speichersystems verwenden, oder Sie können Anmeldeinformationen manuell eingeben, wenn das Speichersystem erkannt wird. Die Details des Speichersystems, das zu ONTAP Tools hinzugefügt wird, werden automatisch an die Erweiterungen weitergeleitet, die Sie in Ihrer Implementierung aktivieren. Sie müssen nicht manuell Storage zu VASA Provider und Storage Replication Adapter (SRA) hinzufügen. Sowohl ONTAP-Tools als auch SRA unterstützen das Hinzufügen von Zugangsdaten auf Cluster-Ebene und SVM-Ebene (Storage Virtual Machine). VASA Provider unterstützt nur Cluster-Level-Anmeldeinformationen zum Hinzufügen von Storage-Systemen. Wenn Sie ein Storage-System hinzufügen, sollte jede Kommunikation zwischen dem ONTAP Tools Plug-in und dem Storage-System gegenseitig authentifiziert werden.

Wenn Ihre Umgebung mehrere vCenter Server-Instanzen umfasst, wird im Dialogfeld Speichersystem hinzufügen ein vCenter Server-Feld angezeigt, in dem Sie angeben können, welcher vCenter Server-Instanz das Speichersystem hinzugefügt werden soll, wenn Sie ein Speichersystem zu ONTAP-Tools hinzufügen. Wenn Sie ein Speichersystem hinzufügen, indem Sie mit der rechten Maustaste auf einen Rechenzentrumsnamen klicken, können Sie keine vCenter Server-Instanz angeben, da der Server bereits mit diesem Datacenter verknüpft ist.

Die Bestandsaufnahme erfolgt auf eine der folgenden Arten. In jedem Fall müssen Sie die Anmeldeinformationen für jedes neu entdeckte Speichersystem angeben.

* Beim Start des ONTAP Tools Service starten die ONTAP Tools ihre automatische Hintergrunderkennung.
* Sie können auf die Schaltfläche *NEU ENTDECKEN* auf der Seite Speichersysteme oder auf einem Host oder Rechenzentrum klicken, um sie im Menü *Aktionen* (*Aktionen* > *NetApp ONTAP Tools* > *Host- und Speicherdaten aktualisieren*) auszuwählen. Sie können auch auf der Registerkarte „erste Schritte“ im Abschnitt „Übersicht“ auf *ENTDECKEN* klicken.


Für alle Funktionen des ONTAP-Tools sind bestimmte Berechtigungen zum Ausführen von Aufgaben erforderlich. Sie können festlegen, was Benutzer basierend auf den mit der ONTAP-Rolle verknüpften Anmeldeinformationen tun können. Alle Benutzer mit demselben Benutzernamen und Kennwort-Paar des Speichersystems nutzen die gleichen Anmeldeinformationen für das Speichersystem und können dieselben Vorgänge ausführen.
