---
permalink: deploy/concept_supported_storage_system_and_applications.html 
sidebar: sidebar 
keywords:  
summary: Bevor Sie mit der Implementierung der ONTAP Tools für VMware vSphere beginnen, sollten Sie die grundlegenden Anforderungen an das Storage-System, die Applikations- und Lizenzierungsanforderungen kennen. 
---
= Unterstützte Storage-Systeme, Lizenzen und Applikationen für die ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie mit der Implementierung der ONTAP Tools für VMware vSphere beginnen, sollten Sie die grundlegenden Anforderungen an das Storage-System, die Applikations- und Lizenzierungsanforderungen kennen.

Das Interoperabilitäts-Matrix-Tool (IMT) enthält die neuesten Informationen zu unterstützten Versionen von ONTAP, vCenter Server, ESXi Hosts, Plug-in-Applikationen und Site Recovery Manager (SRM).

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Interoperabilitäts-Matrix-Tool"^]

Sie müssen die FlexClone Lizenz aktivieren, um Snapshot-Vorgänge für Virtual Machines und Klonvorgänge für VMware Virtual Volumes (VVols) Datastores durchzuführen.

Storage Replication Adapter (SRA) erfordert die folgenden Lizenzen:

* SnapMirror Lizenz
+
Sie müssen die SnapMirror Lizenz aktivieren, um Failover-Vorgänge für SRA auszuführen.

* FlexClone Lizenz
+
Sie müssen die FlexClone Lizenz aktivieren, um Test-Failover-Vorgänge für SRA durchzuführen.



Um die IOPS für einen Datastore anzuzeigen, müssen Sie entweder die Storage-I/O-Steuerung aktivieren oder das Kontrollkästchen „Storage-I/O-Statistiksammlung deaktivieren“ in der Konfiguration des Storage-I/O-Steuersystems deaktivieren. Sie können die Storage-I/O-Steuerung nur aktivieren, wenn Sie über die Enterprise Plus-Lizenz von VMware verfügen.

* https://kb.vmware.com/s/article/1022091["Fehlerbehebung bei der Storage-I/O-Steuerung"]
* https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-37CC0E44-7BC7-479C-81DC-FFFC21C1C4E3.html["Anforderungen an die Storage-I/O-Kontrolle"]

