---
permalink: deploy/concept_how_to_download_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: Sie können die .ova-Datei für ONTAP-Tools für VMware vSphere von der NetApp Support-Website herunterladen. 
---
= So laden Sie ONTAP-Tools herunter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die herunterladen `.zip` Datei, die Binärdateien (_.ova_) und signierte Zertifikate für die ONTAP-Tools für VMware vSphere vom enthält https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support Website"^].

Die Datei _.ova_ enthält die ONTAP-Tools. Nach Abschluss der Implementierung werden VSC, VASA und SRA Produkte in der Kundenumgebung installiert. Standardmäßig funktioniert VSC bereits, wenn Sie ein Folgemodell nutzen möchten und wählen, ob Sie VASA Provider und SRA basierend auf den Anforderungen aktivieren möchten.

Wenn Sie SRA bei der Implementierung von ONTAP-Tools aktivieren möchten, müssen Sie das SRA-Plug-in auf dem Site Recovery Manager (SRM) Server installiert haben. Sie können die Installationsdatei für das SRA-Plug-in im Menü *Storage Replication Adapter für ONTAP* im Abschnitt Software-Downloads herunterladen.
