---
permalink: deploy/concept_how_to_download_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: Sie können die .ova-Datei für ONTAP-Tools für VMware vSphere von der NetApp Support-Website herunterladen. 
---
= So laden Sie ONTAP-Tools herunter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Datei _.ova_ für ONTAP Tools für VMware vSphere von der NetApp Support-Website herunterladen.

Die Datei _.ova_ enthält die ONTAP-Tools. Nach Abschluss der Implementierung sind alle drei Produkte in Ihrer Umgebung installiert. Standardmäßig funktioniert VSC bereits, wenn Sie ein Folgemodell nutzen möchten und wählen, ob Sie VASA Provider und SRA basierend auf den Anforderungen aktivieren möchten.

Sie können ONTAP Tools von herunterladen https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support Website"] Mit der Software Download-Seite.

Wenn Sie SRA bei der Implementierung von ONTAP-Tools aktivieren möchten, müssen Sie das SRA-Plug-in auf dem Site Recovery Manager (SRM) Server installiert haben. Sie können die Installationsdatei für das SRA-Plug-in im Menü *Storage Replication Adapter für ONTAP* im Abschnitt Software-Downloads herunterladen.
