---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: 'Standardmäßig verwendet Virtual Storage Console \(VSC\) festgelegte Ports, um die Kommunikation zwischen seinen Komponenten, einschließlich Storage-Systemen und dem VMware vCenter Server, zu ermöglichen. Wenn Firewalls aktiviert sind, müssen Sie sicherstellen, dass die Firewalls so eingestellt sind, dass Ausnahmen zugelassen werden.' 
---
= Port-Anforderungen für VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig verwendet die Virtual Storage Console (VSC) bestimmte Ports, um die Kommunikation zwischen ihren Komponenten zu ermöglichen. Dazu gehören Storage-Systeme und VMware vCenter Server. Wenn Firewalls aktiviert sind, müssen Sie sicherstellen, dass die Firewalls so eingestellt sind, dass Ausnahmen zugelassen werden.

Bei Firewalls anderer als Windows sollten Sie manuell Zugriff auf bestimmte Ports gewähren, die von VSC verwendet werden. Wenn Sie diesen Ports keinen Zugriff gewähren, wird eine Fehlermeldung wie die folgende angezeigt.

`Unable to communicate with the server.`

VSC verwendet die folgenden bidirektionalen TCP-Standardports:

|===


| *Standardanschlussnummer* | *Beschreibung* 


 a| 
9083
 a| 
Bei Aktivierung verwenden sowohl VASA Provider als auch Storage Replication Adapter (SRA) diesen Port zur Kommunikation mit dem vCenter Server. Dieser Port wird auch zum Abrufen der TCP/IP-Einstellungen benötigt.



 a| 
443
 a| 
Je nach Konfiguration Ihrer Anmeldedaten achten VMware vCenter Server und die Speichersysteme auf die sichere Kommunikation auf diesem Port.



 a| 
8143
 a| 
VSC wartet auf eine sichere Kommunikation von diesem Port.



 a| 
7
 a| 
VSC sendet eine Echo-Anfrage an ONTAP zur Überprüfung der Erreichbarkeit. Diese ist nur beim Hinzufügen eines Storage-Systems erforderlich und kann später deaktiviert werden.

|===

NOTE: Sie sollten das Internet Control Message Protocol (ICMP) aktivieren, bevor Sie die ONTAP-Tools bereitstellen.

Wenn ICMP deaktiviert ist, schlägt die Erstkonfiguration von ONTAP-Tools fehl, und VSC kann die VSC- und VASA-Provider-Services nach der Implementierung nicht starten. Nach der Implementierung müssen Sie die VSC- und VASA-Provider-Services manuell aktivieren.
