---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: Standardmäßig verwenden ONTAP-Tools bestimmte Ports, um die Kommunikation zwischen ihren Komponenten, zu denen Storage-Systeme und der VMware vCenter Server gehören, zu ermöglichen. Wenn Firewalls aktiviert sind, müssen Sie sicherstellen, dass die Firewalls so eingestellt sind, dass Ausnahmen zugelassen werden. 
---
= Port-Anforderungen für ONTAP-Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig verwenden ONTAP-Tools bestimmte Ports, um die Kommunikation zwischen ihren Komponenten, zu denen Storage-Systeme und der VMware vCenter Server gehören, zu ermöglichen. Wenn Firewalls aktiviert sind, müssen Sie sicherstellen, dass die Firewalls so eingestellt sind, dass Ausnahmen zugelassen werden.

Bei Firewalls, die nicht Windows sind, sollten Sie manuell Zugriff auf bestimmte Ports gewähren, die von ONTAP-Tools verwendet werden. Wenn Sie diesen Ports keinen Zugriff gewähren, wird eine Fehlermeldung wie die folgende angezeigt.

`Unable to communicate with the server.`

ONTAP-Tools verwenden die folgenden bidirektionalen TCP-Standardports:

|===


| *Standardanschlussnummer* | *Beschreibung* 


 a| 
9083
 a| 
Bei Aktivierung verwenden sowohl VASA Provider als auch Storage Replication Adapter (SRA) diesen Port zur Kommunikation mit dem vCenter Server. Dieser Port wird auch zum Abrufen der TCP/IP-Einstellungen benötigt. Dieser Port dient zum Herunterladen des VP-Support-Pakets, zum Zugriff auf die Web-CLI-Benutzeroberfläche und zur Steuerung der Pfadkommunikation von VMware zu VP.



 a| 
443
 a| 
Je nach Konfiguration Ihrer Anmeldedaten achten VMware vCenter Server und die Speichersysteme auf die sichere Kommunikation auf diesem Port. Der Port wird in der Client-Server-Kommunikationsarchitektur verwendet. Der Port 443 ist standardmäßig für sichere Verbindungen aktiviert. Der Client, der beliebige Automatisierungs-Client sein kann, der REST API verwendet, initiiert die Verbindung zum Server und den Datenaustausch mit den Endpunkten.



 a| 
8143
 a| 
Die ONTAP-Tools sorgen für eine sichere Kommunikation über diesen Port. Der Port wird in der Client-Server-Kommunikationsarchitektur verwendet. Der Client, der beliebige Automatisierungs-Client sein kann, der REST API verwendet, initiiert die Verbindung zum Server und den Datenaustausch mit den Endpunkten. Dieser Port ist für ONTAP-Tools-Dienste und für den Export von Serverprotokollen der ONTAP-Tools aktiviert. Die Seite register.html wird auf diesem Port gehostet. Der REST-Schwagger ist an diesem Port freigelegt.

|===

NOTE: Sie sollten das Internet Control Message Protocol (ICMP) aktivieren, bevor Sie die ONTAP-Tools bereitstellen.

Wenn ICMP deaktiviert ist, schlägt die Erstkonfiguration der ONTAP-Tools fehl, und ONTAP-Tools können die ONTAP-Tools und VASA Provider-Dienste nach der Bereitstellung nicht starten. Sie müssen die ONTAP-Tools und VASA Provider-Services nach der Implementierung manuell aktivieren.
