---
permalink: deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Bei den ONTAP Tools für VMware vSphere ist die VASA Provider-Funktion standardmäßig aktiviert. Sie können VMware Virtual Volumes \(VVols\)-Datastores mit den erforderlichen Storage-Funktionsprofilen für jeden VVols-Datastore konfigurieren.' 
---
= Aktivieren Sie VASA Provider zur Konfiguration von virtuellen Datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei den ONTAP Tools für VMware vSphere ist die VASA Provider-Funktion standardmäßig aktiviert. Sie können Datastores von VMware Virtual Volumes (VVols) mit den erforderlichen Storage-Funktionsprofilen für jeden VVols Datastore konfigurieren.

*Was Sie brauchen*

* Sie müssen Ihre vCenter Server-Instanz eingerichtet und ESXi konfiguriert haben.
* Sie müssen ONTAP-Tools eingesetzt haben.


*Über diese Aufgabe*

Wenn die VASA Provider-Funktion deaktiviert ist, bevor ein Upgrade auf die Version 9.7.1 der ONTAP Tools durchgeführt wird, bleibt die VASA Provider-Funktion nach dem Upgrade deaktiviert. In dieser Version können Sie die VVols Replizierungsfunktion für VVols Datastores aktivieren.

*Schritte*

. Melden Sie sich bei der Web-Benutzeroberfläche von VMware vSphere an.
. Klicken Sie im vSphere-Client auf *Menü* > *ONTAP-Tools-Konsole*.
. Klicken Sie Auf *Einstellungen*.
. Klicken Sie auf der Registerkarte Verwaltungseinstellungen auf *Funktionen verwalten*.
. Wählen Sie im Dialogfeld Funktionen managen die VASA Provider-Erweiterung aus, um sie zu aktivieren.
. Wenn Sie die Replikationsfunktion für VVols-Datastores verwenden möchten, verwenden Sie die Schaltfläche *VVols-Replizierung aktivieren* umschalten.
. Geben Sie die IP-Adresse der ONTAP-Tools und das Administratorpasswort ein, und klicken Sie dann auf *Apply*.
+

NOTE: Wenn der Status von VASA Provider auch nach Aktivierung der VASA Provider-Erweiterung als „`Offline`“ angezeigt wird, prüfen Sie den ``/var/log/vmware/vmware-sps/sps.log` Datei für Verbindungsfehler mit VASA Provider oder starten Sie den Service „`vmware-sps`“ neu.





== Registrieren Sie die OnCommand API-Services mit ONTAP 9.6 oder früheren Versionen

Bei Verwendung von ONTAP 9.6 oder einer älteren Version können Sie über das VVols Dashboard nur Details zu VMware Virtual Volumes (VVols) Datastores und Virtual Machines anzeigen, wenn Sie OnCommand API Services für VASA Provider registriert haben, um Daten für die VVols-VM- und Datastore-Berichte abzurufen.

*Was Sie brauchen*

Sie müssen OnCommand API Services 2.1 oder höher von der NetApp Support-Website heruntergeladen haben.


NOTE: Im VVols Dashboard werden die Performance-Kennzahlen nur angezeigt, wenn SAN VVols Datastores und Virtual Machines mit ONTAP 9.3 oder höher konfiguriert werden.

*Schritte*

. Klicken Sie auf der Startseite von ONTAP Tools auf *Einstellungen*.
. Klicken Sie auf der Registerkarte Verwaltungseinstellungen auf *Erweiterung verwalten*.
. Verwenden Sie den Schieberegler „OnCommand-API-Dienste registrieren“, um OnCommand-API-Dienste zu aktivieren.
. Geben Sie die IP-Adresse, den Service-Port und die Anmeldeinformationen für OnCommand-API-Dienste ein.
+
Sie können auch das Dialogfeld „VASA Provider-Erweiterungen managen“ für die folgenden Änderungen verwenden:

+
** So aktualisieren Sie die Registrierung für OnCommand-API-Dienste, wenn Änderungen an den Anmeldedaten vorgenommen werden.
** So können Sie OnCommand API Services wieder aufheben, wenn Sie das VVols Dashboard nicht mehr benötigen.
+
Um die OnCommand API Services-Registrierung für VASA Provider zu entfernen, müssen Sie das Kontrollkästchen OnCommand API Services registrieren deaktivieren.



. Klicken Sie Auf *Anwenden*.
+
Im VVols Dashboard werden die Kennzahlen für ONTAP 9.6 oder frühere SAN VVols-Datastores nur angezeigt, wenn die Registrierung der OnCommand API Services abgeschlossen ist.



*Verwandte Informationen*

https://mysupport.netapp.com/site/global/dashboard["NetApp Support"]
