---
permalink: deploy/task_upgrade_storage_replication_adapter.html 
sidebar: sidebar 
keywords: SRA, upgrade 
summary: 'Nach einem Upgrade von ONTAP-Tools oder der Implementierung der neuesten Version von ONTAP-Tools müssen Sie Ihren Storage Replication Adapter \(SRA\) aktualisieren.' 
---
= Aktualisieren Sie Den Storage Replication Adapter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach einem Upgrade von ONTAP-Tools oder der Implementierung der neuesten Version von ONTAP-Tools müssen Sie Ihren Storage Replication-Adapter (SRA) aktualisieren.

*Schritt*

. Sie müssen ein Upgrade auf den neuesten Adapter anhand einer der folgenden Verfahren durchführen, die auf Ihrem Adapter basieren:
+
|===


| * Für...* | *Ausführen des folgenden...* 


 a| 
Windows
 a| 
.. Melden Sie sich beim SRM Windows Server an.
.. Deinstallieren Sie das vorhandene SRA _.msi_ -Installationsprogramm vom SRM-Server.
.. Ändern Sie den Systempfad in `C:\Program Files\VMware\VMware vCenter Site Recovery Manager\external\perl\c\bin`
.. Doppelklicken Sie auf das Installationsprogramm für _.msi_, das Sie von der NetApp Support-Website heruntergeladen haben, und befolgen Sie die Anweisungen auf dem Bildschirm.
.. Geben Sie die IP-Adresse und das Passwort Ihrer bereitgestellten ONTAP-Tools ein.




 a| 
Appliance-basierter Adapter
 a| 
.. Melden Sie sich auf der Seite SRM Appliance Management an.
.. Klicken Sie auf *Storage Replication Adapter* und klicken Sie auf *Löschen*, um die vorhandene SRA zu entfernen.
.. Klicken Sie Auf *Neuer Adapter* > *Durchsuchen*.
.. Klicken Sie hier, um die aktuelle SRA Tarball-Datei auszuwählen, die Sie von der NetApp Support-Website heruntergeladen haben, und klicken Sie dann auf *Installieren*.
.. Konfigurieren Sie SRA auf der SRM Appliance.
+
link:../protect/task_configure_sra_on_srm_appliance.html["SRA auf der SRM-Appliance wird konfiguriert"]



|===

