---
permalink: protect/concept_migration_of_disaster_recovery_setup_from_windows_to_appliance.html 
sidebar: sidebar 
keywords: Migration 
summary: 'Wenn Sie Windows Based Site Recovery Manager \(SRM\) für Disaster Recovery verwenden und die SRM Appliance für dasselbe Setup verwenden möchten, sollten Sie Ihr Windows Disaster Recovery-Setup auf das Appliance-basierte SRM migrieren.' 
---
= Migration von Windows SRM auf eine SRM Appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Windows-basierten Site Recovery Manager (SRM) für Disaster Recovery verwenden und die SRM-Appliance für dasselbe Setup verwenden möchten, sollten Sie Ihr Windows Disaster Recovery-Setup auf die Appliance-basierte SRM migrieren.

Bei der Migration der Disaster Recovery sind folgende Schritte zu beachten:

. Aktualisieren Sie Ihre vorhandenen ONTAP Tools für die VMware vSphere Appliance auf die neueste Version.
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["Upgraden auf die aktuelle Version von ONTAP-Tools"]

. Migrieren Sie Windows-basierten Storage Replication Adapter auf Appliance-basierte SRA.
. Migrieren von Windows SRM-Daten zur SRM Appliance


Detaillierte Schritte finden Sie unter https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-installation-and-configuration-8-8.html["Installation und Konfiguration von Site Recovery Manager"]
