---
permalink: protect/configure_sra_with_srm_shared_site.html 
sidebar: sidebar 
keywords: SRA with SRM 
summary: ONTAP Tools für VMware vSphere unterstützen die Konfiguration gemeinsam genutzter VMware SRM-Recovery-Standorte. 
---
= Konfigurieren Sie SRA mit SRM in einer Konfiguration mit einem gemeinsam genutzten Recovery-Standort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools für VMware vSphere unterstützen die Konfiguration gemeinsam genutzter SRM-Recovery-Standorte von VMware. Weitere Informationen finden Sie unter: https://docs.vmware.com/en/Site-Recovery-Manager/8.6/com.vmware.srm.install_config.doc/GUID-EBF84252-DF37-43CD-ADC8-E90F5254F315.html["Site Recovery Manager in einer Konfiguration mit gemeinsam genutzten Recovery-Standorten"]. Die Site Recovery Manager Server-Instanzen am Recovery-Standort stellen eine Verbindung zu denselben vCenter Server-Instanzen her.

In einer SRM Shared Recovery Site-Konfiguration benötigt jeder SRM-Server eine dedizierte SRA-Instanz (1:1 Beziehung zwischen SRM und SRA). Konfigurieren Sie OTV im VCF-Modus als dedizierte SRA-Instanz für jeden SRM-Server. Sie können auch eine nicht-SRA-fähige ONTAP-Tools-Appliance implementieren, die in vCenter registriert ist und für nicht-SRA-Aufgaben wie die Bereitstellung von Datastores verwendet wird.

Der https://kb.netapp.com/mgmt/OTV/SRA/Storage_Replication_Adapter%3A_How_to_configure_SRA_in_a_SRM_Shared_Recovery_Site["So konfigurieren Sie SRA an einem SRM Shared Recovery Site"] Der KB-Artikel beschreibt das Verfahren zum Einrichten von SRA zur Unterstützung der Konfiguration eines gemeinsam genutzten SRM-Recovery-Standorts.
