---
permalink: protect/task_protect_non_protected_virtual_machines.html 
sidebar: sidebar 
keywords: virtual machines, configuring protection 
summary: Sie können den Schutz Ihrer vorhandenen ungeschützten Virtual Machines konfigurieren, die mit VM Storage Policy erstellt wurden, wobei die Replizierung deaktiviert ist. Um einen Schutz zu gewährleisten, sollten Sie die VM-Storage-Richtlinie ändern und eine Replizierungsgruppe zuweisen. 
---
= Sicherung ungesicherter Virtual Machines
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Schutz Ihrer vorhandenen ungeschützten Virtual Machines konfigurieren, die mit VM Storage Policy erstellt wurden, wobei die Replizierung deaktiviert ist. Um einen Schutz zu gewährleisten, sollten Sie die VM-Storage-Richtlinie ändern und eine Replizierungsgruppe zuweisen.

*Über diese Aufgabe*

Wenn die SVM sowohl IPv4 als auch IPv6 LIFs hat, sollten Sie IPv6 LIFs deaktivieren und später Disaster-Recovery-Workflows durchführen.

*Schritte*

. Klicken Sie auf die erforderliche Virtual Machine, und vergewissern Sie sich, dass sie mit der VM-Standardspeicherrichtlinie konfiguriert ist.
. Klicken Sie mit der rechten Maustaste auf die ausgewählte virtuelle Maschine und klicken Sie auf *VM Policies* > *VM Storage Policies bearbeiten*.
. Wählen Sie eine VM-Speicherrichtlinie aus, bei der die Replikation aktiviert ist. Klicken Sie dazu im Dropdown-Menü *VM-Speicherrichtlinie* auf.
. Wählen Sie eine Replikationsgruppe aus dem Dropdown-Menü *Replikationsgruppe* aus und klicken Sie dann auf *OK*.
. Überprüfen Sie die Zusammenfassung der virtuellen Maschine, um zu bestätigen, dass die virtuelle Maschine geschützt ist.
+
[NOTE]
====
** Diese Version von ONTAP Tools unterstützt keine laufenden Klone gesicherter Virtual Machines. Sie sollten die Virtual Machine ausschalten und dann den Klonvorgang ausführen.
** Wenn ein Datastore nach einem Reprotect-Vorgang nicht in den ONTAP-Tools angezeigt wird, sollten Sie eine Storage-System-Erkennung ausführen oder auf die nächste geplante Bestandsaufnahme warten.


====

