---
permalink: protect/task_configure_storage_replication_adapter_for_san_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Sie müssen die Speichersysteme einrichten, bevor Sie Storage Replication Adapter \(SRA\) für Site Recovery Manager \(SRM\) ausführen.' 
---
= Konfigurieren Sie Storage Replication Adapter für die SAN-Umgebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Storage-Systeme einrichten, bevor Sie Storage Replication Adapter (SRA) für Site Recovery Manager (SRM) ausführen.

ONTAP Tools für VMware vSphere unterstützen die Konfiguration gemeinsam genutzter SRM-Recovery-Standorte von VMware. Weitere Informationen finden Sie unter: https://docs.vmware.com/en/Site-Recovery-Manager/8.6/com.vmware.srm.install_config.doc/GUID-EBF84252-DF37-43CD-ADC8-E90F5254F315.html["Site Recovery Manager in einer Konfiguration mit gemeinsam genutzten Recovery-Standorten"].

Der https://kb.netapp.com/mgmt/OTV/SRA/Storage_Replication_Adapter%3A_How_to_configure_SRA_in_a_SRM_Shared_Recovery_Site["So konfigurieren Sie SRA an einem SRM Shared Recovery Site"] Der KB-Artikel beschreibt das Verfahren zum Einrichten von SRA zur Unterstützung der Konfiguration eines gemeinsam genutzten SRM-Recovery-Standorts.

*Was Sie brauchen*

Sie müssen die folgenden Programme auf dem geschützten Standort und dem Wiederherstellungsstandort installiert haben:

* SRM
+
Dokumentation zur Installation von SRM befindet sich auf der VMware Site.

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager - Dokumentation"]

* SRA
+
Der Adapter wird entweder auf SRM installiert.



*Schritte*

. Vergewissern Sie sich, dass die primären ESXi-Hosts mit den LUNs im primären Speichersystem am geschützten Standort verbunden sind.
. Vergewissern Sie sich, dass die LUNS in Initiatorgruppen vorhanden sind, die über die verfügen `ostype` Option auf dem primären Storage-System auf _VMware_ eingestellt.
. Vergewissern Sie sich, dass die ESXi-Hosts am Recovery-Standort über entsprechende FC- oder iSCSI-Konnektivität zur Storage Virtual Machine (SVM) verfügen. Die ESXi-Hosts der sekundären Site sollten Zugriff auf den sekundären Standort-Storage haben, ebenso sollten die ESXi-Hosts des primären Standorts Zugriff auf den primären Standort-Storage haben.
+
Dazu müssen Sie entweder überprüfen, ob die ESXi Hosts über lokale LUNs auf der SVM verbunden sind, oder Sie verwenden die `fcp show initiators` Befehl oder das `iscsi show initiators` Befehl auf den SVMs. Überprüfen Sie den LUN-Zugriff für die zugeordneten LUNs in ESXi, um die FC- und iSCSI-Konnektivität zu überprüfen.





== Konfigurieren Sie Storage Replication Adapter für NAS-Umgebungen

*Was Sie brauchen*

Sie müssen die folgenden Programme auf dem geschützten Standort und dem Wiederherstellungsstandort installiert haben:

* SRM
+
Dokumentation zur Installation von SRM finden Sie auf der VMware-Website.

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager - Dokumentation"]

* SRA
+
Der Adapter wird auf SRM und dem SRA Server installiert.



*Schritte*

. Überprüfen Sie, ob die Datenspeicher am geschützten Standort virtuelle Maschinen enthalten, die bei vCenter Server registriert sind.
. Überprüfen Sie, ob die ESXi-Hosts am geschützten Standort die NFS-Exporte-Volumes von der Storage Virtual Machine (SVM) gemountet haben.
. Überprüfen Sie, ob gültige Adressen wie die IP-Adresse, der Hostname oder der FQDN, auf denen die NFS-Exporte vorhanden sind, im Feld *NFS-Adressen* angegeben sind, wenn Sie den Array Manager-Assistenten zum Hinzufügen von Arrays zu SRM verwenden.
. Verwenden Sie die `ping` Führen Sie einen Befehl auf jedem ESXi Host am Recovery-Standort aus, um zu überprüfen, ob der Host über einen VMkernel-Port verfügt, der auf die IP-Adressen zugreifen kann, die für NFS-Exporte von der SVM verwendet werden.


https://mysupport.netapp.com/site/global/dashboard["NetApp Support"]
