---
permalink: protect/task_update_sra_credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Damit SRM mit SRA kommunizieren kann, sollten Sie die SRA-Anmeldedaten auf dem SRM-Server aktualisieren, wenn Sie die Anmeldedaten geändert haben. 
---
= SRA-Anmeldedaten aktualisieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Damit SRM mit SRA kommunizieren kann, sollten Sie die SRA-Anmeldedaten auf dem SRM-Server aktualisieren, wenn Sie die Anmeldedaten geändert haben.

Sie müssen das Kennwort für den Benutzernamen des SRM-Maschinenordners, der zwischengespeicherte ONTAP-Tools, löschen und den SRA neu installieren.

*Was Sie brauchen*

Sie sollten die im Thema genannten Schritte ausgeführt haben link:../protect/task_configure_sra_on_srm_appliance.html["SRA auf der SRM-Appliance wird konfiguriert"]

*Schritte*

. Führen Sie die folgenden Befehle aus, um das Kennwort für den im Cache gespeicherten ONTAP-Werkzeugordner des SRM-Computers zu löschen:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd /conf`
.. `rm -rf *`


. Führen Sie den Perl-Befehl aus, um SRA mit den neuen Anmeldeinformationen zu konfigurieren:
+
.. `cd ..`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`. Sie benötigen ein einziges Angebot um den Passwortwert herum.
+
Eine Erfolgsmeldung, die bestätigt, dass die Speicher-Anmeldedaten gespeichert werden, wird angezeigt. SRA kann mit dem SRA-Server unter Verwendung der angegebenen IP-Adresse, des Ports und der Anmeldeinformationen kommunizieren.




