---
permalink: protect/task_configure_storage_replication_adapter_for_nas_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Sie müssen die Speichersysteme konfigurieren, bevor Sie Storage Replication Adapter \(SRA\) für VMware vCenter Site Recovery Manager \(SRM\) ausführen.' 
---
= Konfigurieren Sie Storage Replication Adapter für NAS-Umgebungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Storage-Systeme konfigurieren, bevor Sie Storage Replication Adapter (SRA) für VMware vCenter Site Recovery Manager (SRM) ausführen.

*Was Sie brauchen*

Sie müssen die folgenden Programme auf dem geschützten Standort und dem Wiederherstellungsstandort installiert haben:

* SRM
+
Dokumentation zur Installation von SRM finden Sie auf der VMware-Website.

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager - Dokumentation"]

* SRA
+
Der Adapter wird auf SRM und dem SRA Server installiert.



*Schritte*

. Überprüfen Sie, ob die Datenspeicher am geschützten Standort virtuelle Maschinen enthalten, die bei vCenter Server registriert sind.
. Überprüfen Sie, ob die ESXi-Hosts am geschützten Standort die NFS-Exporte-Volumes von der Storage Virtual Machine (SVM) gemountet haben.
. Überprüfen Sie, ob gültige Adressen wie die IP-Adresse, der Hostname oder der FQDN, auf denen die NFS-Exporte vorhanden sind, im Feld *NFS-Adressen* angegeben sind, wenn Sie den Array Manager-Assistenten zum Hinzufügen von Arrays zu SRM verwenden.
. Verwenden Sie den Ping-Befehl für jeden ESXi Host am Recovery-Standort, um zu überprüfen, ob der Host über einen VMkernel-Port verfügt, der auf die IP-Adressen zugreifen kann, die für die Bereitstellung von NFS-Exports von der SVM verwendet werden.


https://mysupport.netapp.com/site/global/dashboard["NetApp Support"]
