---
permalink: protect/task_configure_vm_storage_policies.html 
sidebar: sidebar 
keywords:  
summary: Sie sollten VM-Storage-Richtlinien konfigurieren, um Virtual Machines zu managen, die auf VVols Datastores konfiguriert sind, und um Services wie die Replizierung für die virtuellen Festplatten zu aktivieren. Bei herkömmlichen Datenspeichern kann optional diese VM Storage-Richtlinien verwendet werden. 
---
= Konfiguration von VM Storage Policies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten VM-Storage-Richtlinien konfigurieren, um Virtual Machines zu managen, die auf VVols Datastores konfiguriert sind, und um Services wie die Replizierung für die virtuellen Festplatten zu aktivieren. Bei herkömmlichen Datenspeichern kann optional diese VM Storage-Richtlinien verwendet werden.

*Über diese Aufgabe*

Der vSphere Web-Client bietet Standard-Storage-Richtlinien. Sie können jedoch Richtlinien erstellen und sie den Virtual Machines zuweisen.

*Schritte*

. Klicken Sie auf der Seite vSphere Client auf *Menü* > *Richtlinien und Profile*.
. Klicken Sie auf *VM Storage Policies* > *Create VM Storage Policy*.
. Geben Sie auf der Seite Create VM Storage Policy folgende Details ein:
+
.. Geben Sie einen Namen und eine Beschreibung für die VM-Speicherrichtlinie ein.
.. Wählen Sie * Enable rules für „NetApp Clustered Data ONTAP.VP.vvol“ Storage* aus.
.. Wählen Sie auf der Registerkarte Platzierung das erforderliche Speicherfähigkeitsprofil aus.
.. Wählen Sie die Option *Benutzerdefiniert*, um die Replikation zu aktivieren.
.. Klicken Sie auf *REGEL HINZUFÜGEN*, um *Asynchronous* Replikation und erforderliche SnapMirror Schedule auszuwählen, und klicken Sie dann auf *NEXT*.
.. Überprüfen Sie die aufgeführten kompatiblen Datenspeicher und klicken Sie auf der Registerkarte Speicherkompatibilität auf *NEXT*.
+
Bei VVols Datastores mit Datensicherungs-FlexVol Volumes wird eine Prüfung kompatibler Datastores nicht durchgeführt.



. Überprüfen Sie die Auswahl Ihrer VM-Speicherrichtlinie auf der Registerkarte *Überprüfen und beenden* und klicken Sie dann auf *Fertig stellen*.

