---
permalink: concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Die ONTAP Tools unterstützen eine hochverfügbare \(HA\)-Konfiguration, die eine unterbrechungsfreie Funktionalität von ONTAP Tools bei Ausfällen ermöglicht.' 
---
= Konfigurieren Sie Hochverfügbarkeit für ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die ONTAP Tools unterstützen eine HA-Konfiguration (High Availability), um den unterbrechungsfreien Betrieb von ONTAP Tools bei einem Ausfall sicherzustellen.

Die ONTAP Tools basieren auf der VMware vSphere HA-Funktion (High Availability, Hochverfügbarkeit) und der vSphere-Fehlertoleranz (FT)-Funktion, um eine hohe Verfügbarkeit zu gewährleisten. Die Hochverfügbarkeitslösung (HA) sorgt für ein schnelles Recovery nach Ausfällen, die auf folgende Komponenten zurückzuführen sind:

* Host-Ausfall
* Netzwerkausfall
* Fehler bei Virtual Machine (Ausfall des Gastbetriebssystems)
* Absturz der Applikation (ONTAP-Tools)


Um Hochverfügbarkeit zu gewährleisten, ist für ONTAP Tools keine zusätzliche Konfiguration erforderlich. Nur vCenter-Server und ESXi-Hosts müssen mit der VMware vSphere HA-Funktion oder der vSphere FT-Funktion basierend auf ihren Anforderungen konfiguriert werden. Sowohl HA als AUCH FT erfordern Cluster-Hosts zusammen mit Shared Storage. FT hat zusätzliche Anforderungen und Einschränkungen.

Zusätzlich zur VMware vSphere HA Lösung und der vSphere FT Lösung unterstützen ONTAP Tools auch dabei, die ONTAP Tools ständig verfügbar zu halten. Der Watchdog-Prozess der ONTAP-Tools überwacht regelmäßig alle drei Dienste und startet sie automatisch neu, wenn Fehler erkannt werden. So wird Applikationsausfälle verhindert.


NOTE: VCenter HA wird nicht durch ONTAP Tools unterstützt.



== VMware vSphere HA

Sie können Ihre vSphere Umgebung konfigurieren, in der ONTAP Tools für VMware vSphere für Hochverfügbarkeit implementiert werden. Die VMware HA-Funktion bietet Failover-Schutz vor Hardware-Ausfällen und Ausfällen des Betriebssystems in virtuellen Umgebungen.

Die VMware HA Funktion überwacht Virtual Machines und erkennt so Betriebssystemausfälle und Hardwareausfälle. Wenn ein Fehler erkannt wird, startet die VMware HA-Funktion die virtuellen Maschinen auf den anderen physischen Servern im Ressourcenpool neu. Wenn ein Serverfehler erkannt wird, ist keine manuelle Intervention erforderlich.

Das Verfahren zur Konfiguration von VMware HA hängt von der Version des vCenter Servers ab. Sie können beispielsweise den folgenden Referenzlink verwenden und die erforderliche vCenter Server-Version auswählen, um die Schritte zum Konfigurieren von VMware HA anzuzeigen.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.avail.doc/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html["VMware vSphere Dokumentation: Erstellen und Verwenden von vSphere HA-Clustern"]



== Fehlertoleranz für VMware vSphere

Die VMware vSphere Fault Tolerance (FT) Funktion bietet Hochverfügbarkeit auf höherer Ebene und ermöglicht es Ihnen, Virtual Machines ohne Datenverlust oder Verbindungen zu schützen. Sie müssen vSphere FT für ONTAP Tools von Ihrem vCenter Server aktivieren oder deaktivieren.

Stellen Sie sicher, dass Ihre vSphere Lizenz FT mit der Anzahl der vCPUs unterstützt, die für ONTAP Tools in Ihrer Umgebung benötigt wird (mindestens 2 vCPUs; 4 vCPUs für große Umgebungen).

VSphere FT ermöglicht den Betrieb von Virtual Machines selbst bei Serverausfällen. Wenn vSphere FT auf einer virtuellen Maschine aktiviert ist, wird automatisch eine Kopie der primären virtuellen Maschine auf einem anderen Host (der sekundären virtuellen Maschine) erstellt, der vom Distributed Resource Scheduler (DRS) ausgewählt wird. Wenn DRS nicht aktiviert ist, wird der Zielhost von den verfügbaren Hosts ausgewählt. VSphere FT betreibt die primäre virtuelle Maschine und die sekundäre virtuelle Maschine im Sperrmodus, wobei jeder den Ausführungsstatus der primären Virtual Machine auf die sekundäre Virtual Machine spiegelt.

Wenn ein Hardwarefehler auftritt, der dazu führt, dass die primäre virtuelle Maschine ausfällt, nimmt die sekundäre virtuelle Maschine sofort dort auf, wo die primäre virtuelle Maschine angehalten wurde. Die sekundäre Virtual Machine wird weiterhin ohne Verlust von Netzwerkverbindungen, Transaktionen oder Daten ausgeführt.

Ihr System muss die CPU-Anforderungen, die Grenzwerte für virtuelle Maschinen sowie die Lizenzierungsanforderungen für die Konfiguration von vSphere FT für Ihre vCenter Server-Instanz erfüllen.

Das Verfahren zur HA-Konfiguration hängt von der Version des vCenter Servers ab. Sie können beispielsweise den folgenden Referenzlink verwenden und die erforderliche vCenter Server-Version auswählen, um die Schritte zum Konfigurieren von HA anzuzeigen.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.avail.doc/GUID-57929CF0-DA9B-407A-BF2E-E7B72708D825.html["VMware vSphere Dokumentation: Fehlertoleranz, Beschränkungen und Lizenzierung"]
