---
permalink: concepts/concept_virtual_storage_console_overview.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools für VMware vSphere bieten ein lückenloses Lifecycle Management für Virtual Machines in VMware Umgebungen, die NetApp Storage-Systeme nutzen. So können Administratoren den Storage direkt innerhalb von vCenter Server managen und vereinfachen somit das Storage- und Datenmanagement für VMware Umgebungen. 
---
= Übersicht über die ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools für VMware vSphere bieten ein lückenloses Lifecycle Management für Virtual Machines in VMware Umgebungen, die NetApp Storage-Systeme nutzen. So können Administratoren den Storage direkt innerhalb von vCenter Server managen und vereinfachen somit das Storage- und Datenmanagement für VMware Umgebungen.

Die ONTAP Tools lassen sich in vSphere Client integrieren und ermöglichen die Verwendung von SSO-Services (Single Sign On). In einer Umgebung mit mehreren vCenter Server-Instanzen muss jede vCenter Server-Instanz, die Sie managen möchten, über eine eigene registrierte Instanz von ONTAP-Tools verfügen.

Jede Komponente der ONTAP Tools verfügt über Funktionen zur effizienteren Verwaltung Ihres Storage.

Das Plug-in-Tool VMware vSphere Client wurde entwickelt, um Plug-in-Funktionen in den vSphere Client zu integrieren, ohne dass es in vCenter Server ausgeführt werden muss. Dies sorgt für eine Isolierung von Plug-ins und ermöglicht die horizontale Skalierung von Plug-ins in großen vSphere Umgebungen.



== Virtual Storage Console (VSC)

Mit VSC führen Sie die folgenden Aufgaben aus:

* Fügen Sie Storage-Controller hinzu, weisen Sie Zugangsdaten zu und richten Sie Berechtigungen für Storage Controller von VSC ein, von denen sowohl SRA als auch VASA Provider profitieren können
* Bereitstellung von Datenspeichern
* Überwachen Sie die Performance von Datastores und Virtual Machines in Ihrer vCenter Server Umgebung
* Steuern Sie den Administratorzugriff auf vCenter Server-Objekte, indem Sie die rollenbasierte Zugriffssteuerung (Role-Based Access Control, RBAC) auf zwei Ebenen nutzen:
+
** VSphere Objekte wie Virtual Machines und Datastores
+
Diese Objekte werden über die vCenter Server RBAC gemanagt.

** ONTAP Storage
+
Die Storage-Systeme werden über die rollenbasierte Zugriffssteuerung von ONTAP gemanagt.



* Die Host-Einstellungen der ESXi Hosts, die mit NetApp Storage verbunden sind, anzeigen und aktualisieren


VSC Bereitstellungsvorgänge profitieren vom Einsatz des NFS-Plug-ins für VMware vStorage APIs für Array Integration (VAAI). Das NFS-Plug-in für VAAI ist eine Softwarebibliothek, in der die VMware Virtual Disk Libraries integriert sind, die auf dem ESXi-Host installiert sind. Das Paket VMware VAAI ermöglicht die Auslagerung bestimmter Aufgaben von den physischen Hosts an das Storage Array. Aufgaben wie Thin Provisioning und Hardwarebeschleunigung können auf Array-Ebene ausgeführt werden, um die Workloads auf den ESXi Hosts zu verringern. Die Funktion zum Offload und zur Speicherplatzreservierung verbessern die Performance des VSC-Betriebs.

Das NetApp NFS Plug-in für VAAI wird nicht mit VSC ausgeliefert. Aber Sie können das Plug-in-Installationspaket herunterladen und Anweisungen zum Installieren des Plug-ins über die NetApp Support Site erhalten.



== VASA Provider

VASA Provider für ONTAP sendet Informationen über den von VMware vSphere APIs for Storage Awareness (VASA) verwendeten Storage an den vCenter Server. Die ONTAP Tools sind mit VSC über VASA Provider integriert. VASA Provider ermöglicht Ihnen die Ausführung der folgenden Aufgaben:

* Bereitstellen von Datastores mit VMware Virtual Volumes (VVols)
* Erstellen und nutzen Sie Storage-Funktionsprofile, um unterschiedliche Storage Service Level Objectives (SLOs) für die Umgebung zu definieren
* Überprüfen Sie die Compliance zwischen den Datastores und den Storage-Funktionsprofilen
* Legen Sie Alarme fest, um zu warnen, wenn Volumes und Aggregate sich den Schwellenwerten nähern
* Überwachen Sie die Performance von Virtual Machine Disks (VMDKs) und den Virtual Machines, die auf VVols Datastores erstellt werden




== Storage Replication Adapter (SRA)

Wenn SRA aktiviert und in Verbindung mit VMware Site Recovery Manager (SRM) verwendet wird, können bei einem Ausfall die vCenter Server-Datenspeicher und die Virtual Machines wiederhergestellt werden. SRA ermöglicht die Nutzung einer Array-basierten Replizierung (ABR) für geschützte Standorte und Recovery-Standorte bei einem Ausfall zur Disaster Recovery.

*Verwandte Informationen*

https://mysupport.netapp.com/site/global/dashboard["NetApp Support"]
