---
permalink: concepts/concept_standard_roles_packaged_with_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Um die Arbeit mit vCenter Server-Berechtigungen und rollenbasierter Zugriffssteuerung \ (RBAC\) zu vereinfachen, bieten ONTAP Tools standardmäßige ONTAP Tools, mit denen Sie wichtige Aufgaben im Zusammenhang mit ONTAP Tools ausführen können. Es gibt auch eine schreibgeschützte Rolle, mit der Sie die Informationen anzeigen, aber keine Aufgaben ausführen können.' 
---
= Standardrollen in Paket mit ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Arbeit mit vCenter Server-Berechtigungen und rollenbasierter Zugriffssteuerung (Role Based Access Control, RBAC) zu vereinfachen, bieten die ONTAP Tools standardmäßige ONTAP-Tools, mit denen Sie wichtige ONTAP-Tools-Aufgaben ausführen können. Es gibt auch eine schreibgeschützte Rolle, mit der Sie die Informationen anzeigen, aber keine Aufgaben ausführen können.

Die Standard-ONTAP-Tool-Rollen verfügen sowohl über die erforderlichen spezifischen Berechtigungen für ONTAP-Tools als auch über die nativen vCenter Server-Berechtigungen, die Benutzer zum Ausführen von ONTAP-Tools-Aufgaben benötigen. Darüber hinaus werden die Rollen so eingerichtet, dass sie über die erforderlichen Berechtigungen für alle unterstützten Versionen des vCenter Servers verfügen.

Als Administrator können Sie diese Rollen bei Bedarf Benutzern zuweisen.


NOTE: Wenn Sie ONTAP-Tools auf die neueste Version aktualisieren, werden die Standardrollen automatisch aktualisiert, um mit der neuen Version des Tools zu arbeiten.

Sie können die Standardrollen der ONTAP-Tools anzeigen, indem Sie auf der vSphere Client-Startseite auf *Rollen* klicken.

Mit den Rollen, die ONTAP-Tools zur Verfügung stellen, können Sie die folgenden Aufgaben ausführen:

|===


| * Rolle* | *Beschreibung* 


 a| 
VSC Administrator
 a| 
Bietet alle nativen vCenter Server-Berechtigungen und ONTAP-Tools-spezifischen Berechtigungen, die für die Ausführung aller ONTAP-Tools-Aufgaben erforderlich sind.



 a| 
VSC schreibgeschützt
 a| 
Bietet schreibgeschützten Zugriff auf ONTAP Tools. Diese Benutzer können keine ONTAP-Tools-Aktionen ausführen, die über Zugriffskontrollmöglichkeiten verfügen.



 a| 
VSC Provisionierung
 a| 
Bietet alle nativen vCenter Server-Berechtigungen und ONTAP-Tools-spezifischen Berechtigungen, die für die Bereitstellung von Speicher erforderlich sind. Sie können die folgenden Aufgaben ausführen:

* Erstellen neuer Datenspeicher
* Datastores zerstören
* Zeigt Informationen zu Storage-Funktionsprofilen an


|===


== Richtlinien zur Verwendung von Standardrollen in ONTAP-Tools

Wenn Sie mit standardmäßigen ONTAP-Tools für VMware vSphere-Rollen arbeiten, gibt es bestimmte Richtlinien, die Sie befolgen sollten.

Sie sollten die Standardrollen nicht direkt ändern. Wenn Sie dies tun, überschreiben ONTAP-Tools Ihre Änderungen bei jedem Upgrade. Das Installationsprogramm aktualisiert die Standardrollendefinitionen jedes Mal, wenn Sie ONTAP-Tools aktualisieren. Dadurch wird sichergestellt, dass die Rollen für Ihre Version von ONTAP-Tools sowie für alle unterstützten Versionen von vCenter Server aktuell sind.

Sie können jedoch die Standardrollen verwenden, um Rollen zu erstellen, die auf Ihre Umgebung zugeschnitten sind. Dazu sollten Sie die Standardrolle „ONTAP Tools“ kopieren und dann die kopierte Rolle bearbeiten. Wenn Sie eine neue Rolle erstellen, können Sie diese Rolle auch dann beibehalten, wenn Sie den Windows-Dienst für ONTAP-Tools neu starten oder aktualisieren.

Folgende Standardrollen für ONTAP-Tools können u. a. verwendet werden:

* Verwenden Sie die Standardrollen der ONTAP-Tools für alle Aufgaben mit ONTAP-Tools.
+
In diesem Szenario bieten die Standardrollen alle Berechtigungen, die ein Benutzer zur Ausführung der Aufgaben der ONTAP-Tools benötigt.

* Kombinieren Sie Rollen, um die Aufgaben zu erweitern, die ein Benutzer ausführen kann.
+
Wenn die Standard-ONTAP-Tools-Rollen zu viel Granularität für Ihre Umgebung bieten, können Sie die Rollen erweitern, indem Sie Gruppen auf höherer Ebene erstellen, die mehrere Rollen enthalten.

+
Wenn ein Benutzer andere Aufgaben, die nicht zu ONTAP gehören, ausführen muss, für die zusätzliche native vCenter Server-Berechtigungen erforderlich sind, können Sie eine Rolle erstellen, die diese Berechtigungen bereitstellt, und diese auch der Gruppe hinzufügen.

* Erstellung feingranularer Rollen
+
Wenn in Ihrem Unternehmen Rollen implementiert werden müssen, die restriktiver sind als die Standardrollen für ONTAP-Tools, können Sie mithilfe der Rollen im Bereich ONTAP-Tools neue Rollen erstellen.

+
In diesem Fall klonen Sie die erforderlichen Rollen der ONTAP-Tools und bearbeiten dann die geklonte Rolle, sodass nur die Berechtigungen zum Benutzer gehören.


