---
permalink: concepts/concept_how_to_configure_data_ontap_role_based_access_control_for_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Sie müssen die rollenbasierte Zugriffssteuerung \(RBAC\) von ONTAP auf dem Storage-System konfigurieren, wenn Sie die rollenbasierte Zugriffssteuerung mit ONTAP-Tools für VMware vSphere verwenden möchten. Über die ONTAP Funktion zur rollenbasierten Zugriffssteuerung können Sie ein oder mehrere benutzerdefinierte Benutzerkonten mit begrenzten Zugriffsberechtigungen erstellen.' 
---
= So konfigurieren Sie die rollenbasierte ONTAP-Zugriffssteuerung für ONTAP Tools für VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die rollenbasierte Zugriffssteuerung (RBAC) von ONTAP auf dem Storage-System konfigurieren, wenn Sie eine rollenbasierte Zugriffssteuerung mit ONTAP Tools für VMware vSphere verwenden möchten. Über die ONTAP Funktion zur rollenbasierten Zugriffssteuerung können Sie ein oder mehrere benutzerdefinierte Benutzerkonten mit begrenzten Zugriffsberechtigungen erstellen.

ONTAP Tools und SRA können auf Storage-Systeme entweder auf Cluster-Ebene oder auf SVM-Ebene (Storage Virtual Machine) zugreifen. Wenn Sie Storage-Systeme auf Cluster-Ebene hinzufügen, müssen Sie die Anmeldedaten des Admin-Benutzers angeben, um alle erforderlichen Funktionen bereitzustellen. Wenn Sie Storage-Systeme durch direktes Hinzufügen von SVM-Details hinzufügen, müssen Sie beachten, dass der Benutzer „`vsadmin`“ nicht über alle erforderlichen Rollen und Funktionen zum Ausführen bestimmter Aufgaben verfügt.

VASA Provider kann nur auf Cluster-Ebene auf Storage-Systeme zugreifen. Wenn VASA Provider für einen bestimmten Storage-Controller erforderlich ist, muss das Storage-System zu ONTAP Tools auf Cluster-Ebene hinzugefügt werden, selbst wenn Sie ONTAP Tools oder SRA verwenden.

Um einen neuen Benutzer zu erstellen und ein Cluster oder eine SVM mit ONTAP-Tools zu verbinden, sollten Sie Folgendes durchführen:

* Erstellen Sie einen Cluster-Administrator oder eine SVM-Administratorrolle mit ONTAP System Manager 9.8P1 oder höher. Siehe link:../configure/task_configure_user_role_and_privileges.html["Konfigurieren von Benutzerrollen und -Berechtigungen"] Finden Sie weitere Informationen.
* Erstellen Sie Benutzer mit der zugewiesenen Rolle und dem entsprechenden Anwendungssatz mithilfe von ONTAP
+
Sie benötigen diese Anmeldedaten für das Storage-System, um die Storage-Systeme für ONTAP Tools zu konfigurieren. Sie können Storage-Systeme für ONTAP Tools konfigurieren, indem Sie die Zugangsdaten in die ONTAP Tools eingeben. Jedes Mal, wenn Sie sich mit diesen Zugangsdaten bei einem Storage-System anmelden, haben Sie Berechtigungen für die ONTAP-Tools-Funktionen, die Sie in ONTAP eingerichtet hatten, während Sie die Anmeldedaten erstellen.

* Fügen Sie das Storage-System zu den ONTAP Tools hinzu und geben Sie die Anmeldeinformationen des soeben erstellten Benutzers an




== Rollen in ONTAP Tools

ONTAP-Tools klassifiziert die ONTAP-Berechtigungen in die folgenden Rollen von ONTAP-Tools:

* Ermitteln
+
Ermöglicht die Erkennung aller verbundenen Storage Controller

* Speicher Erstellen
+
Ermöglicht die Erstellung von Volumes und LUNs (Logical Unit Number)

* Speicher Ändern
+
Ermöglicht die Anpassung und Deduplizierung von Storage-Systemen

* Speicher Zerstören
+
Aktiviert die Zerstörung von Volumes und LUNs





== VASA Provider-Rollen

Sie können nur richtlinienbasiertes Management auf Cluster-Ebene erstellen. Diese Rolle ermöglicht ein richtlinienbasiertes Storage Management mithilfe von Storage-funktionsprofilen.



== SRA-Rollen

SRA klassifiziert die ONTAP-Berechtigungen als SAN- oder NAS-Rolle auf Cluster-Ebene oder SVM-Ebene. So können Benutzer SRM-Vorgänge ausführen.

ONTAP-Tools führen eine Erstvalidierung von Berechtigungen für RBAC-Rollen von ONTAP durch, wenn Sie den Cluster zu ONTAP Tools hinzufügen. Wenn Sie eine direkte SVM-Storage-IP hinzugefügt haben, führen die ONTAP-Tools die erste Validierung nicht durch. ONTAP-Tools prüfen und erzwingt die Berechtigungen später im Task-Workflow.
