---
permalink: concepts/reference_metrocluster_configurations_supported_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: Die ONTAP Tools für VMware vSphere unterstützen Umgebungen, die MetroCluster IP- und FC-Konfigurationen für ONTAP verwenden. Der Support erfolgt meistens automatisch. Unter Umständen können Sie bei Verwendung einer MetroCluster Umgebung mit VSC und VASA Provider jedoch einige Unterschiede feststellen. 
---
= Von ONTAP Tools unterstützte MetroCluster Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die ONTAP Tools für VMware vSphere unterstützen Umgebungen, die MetroCluster IP- und FC-Konfigurationen für ONTAP verwenden. Der Support erfolgt meistens automatisch. Unter Umständen können Sie bei Verwendung einer MetroCluster Umgebung mit VSC und VASA Provider jedoch einige Unterschiede feststellen.


NOTE: SRA unterstützt keine MetroCluster-Konfigurationen.



== MetroCluster Konfigurationen und VSC

Sie müssen sicherstellen, dass die VSC die Storage-System-Controller am primären und sekundären Standort erkennt. In der Regel erkennt VSC automatisch Storage Controller. Wenn Sie eine Cluster-Management-LIF verwenden, empfehlen wir, sicherzustellen, dass die VSC die Cluster an beiden Standorten erkannt hat. Andernfalls können Sie die Storage Controller manuell zur VSC hinzufügen. Sie können auch den Benutzernamen und die Passwörter, die VSC für die Verbindung zu den Storage Controllern verwendet, ändern.

Bei einem Switchover übernehmen die SVMs am sekundären Standort die over-Performance. Diese SVMs haben das Suffix „`-mc`“ mit ihren Namen angehängt. Falls während eines Umschalttavorgangs z. B. zur Bereitstellung eines Datastores ein Switchover stattfindet, wird der Name der SVM, in der sich der Datastore befindet, so geändert, dass sie das „`-mc`“-Suffix einschließen. Dieses Suffix wird beim Wechsel abgebrochen und die SVMs am primären Standort können die Steuerung fortsetzen.


NOTE: Wenn Sie direkte SVMs mit MetroCluster-Konfiguration zur VSC hinzugefügt haben, dann wird nach der Umschaltung nicht die Änderung des SVM-Namens (hinzugefügt durch das „`-mc`“-Suffix) wiedergegeben. Alle anderen Switchover-Vorgänge werden weiterhin normal ausgeführt.

Wenn ein Switchover oder ein Switchover stattfindet, kann die VSC einige Minuten dauern, um die Cluster automatisch zu erkennen und zu erkennen. Wenn dies während der Durchführung einer VSC-Operation wie der Bereitstellung eines Datenspeichers geschieht, kann es zu Verzögerungen kommen.



== MetroCluster Konfigurationen und VASA Provider

VASA-Provider unterstützt automatisch Umgebungen, die MetroCluster-Konfigurationen verwenden. Die Umschaltung ist in VASA Provider-Umgebungen transparent. Sie können keine direkten SVMs zum VASA Provider hinzufügen.


NOTE: VASA Provider fügt nach einem Switchover das Suffix „`-mc`“ nicht an die Namen der SVMs am sekundären Standort an.
