---
permalink: configure/concept_configure_vsc_for_vmware_vsphere_environment.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools unterstützen eine Vielzahl an Umgebungen. Einige Funktionen in diesen Umgebungen erfordern möglicherweise zusätzliche Konfigurationen. 
---
= Konfigurieren Sie ONTAP Tools für VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools unterstützen eine Vielzahl an Umgebungen. Einige Funktionen in diesen Umgebungen erfordern möglicherweise zusätzliche Konfigurationen.

Möglicherweise müssen Sie einige der folgenden Aufgaben ausführen, um Ihre ESXi-Hosts, Gastbetriebssysteme und ONTAP-Tools zu konfigurieren:

* Überprüfen der ESXi-Hosteinstellungen, einschließlich der UNMAP-Einstellungen
* Hinzufügen von Timeout-Werten für Gastbetriebssysteme
* Erneutes Generieren des SSL-Zertifikats der ONTAP-Tools
* Erstellung von Storage-Funktionsprofilen und Schwellenwertwarnungen
* Ändern der Preferences-Datei, um das Mounten von Datastores über verschiedene Subnetze zu ermöglichen

