---
permalink: configure/reference_esxi_host_values_set_by_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: Mithilfe der ONTAP-Tools für VMware vSphere können Timeouts und andere Werte auf den ESXi-Hosts festgelegt werden, um beste Leistung und erfolgreiches Failover zu gewährleisten. Die Werte der ONTAP Tools basieren auf internen Tests von NetApp. 
---
= ESXi Hostwerte werden mithilfe von ONTAP Tools gesetzt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe der ONTAP-Tools für VMware vSphere können Timeouts und andere Werte auf den ESXi-Hosts festgelegt werden, um beste Leistung und erfolgreiches Failover zu gewährleisten. Die Werte der ONTAP Tools basieren auf internen Tests von NetApp.

Auf einem ESXi-Host können Sie die folgenden Werte festlegen:



== Erweiterte ESXi Konfiguration

* *VMFS3.HardwareAcceleratLocking*
+
Sie sollten diesen Wert auf 1 setzen.

* *VMFS3.EnableBlockDelete*
+
Sie sollten diesen Wert auf 0 setzen.





== NFS-Einstellungen

* *Net.TcpipHeapSize*
+
Setzen Sie diesen Wert auf 32.

* *Net.TcpipHeapMax*
+
Setzen Sie diesen Wert auf 1024 MB.

* *NFS.MaxVolumes*
+
Setzen Sie diesen Wert auf 256.

* *NFS41.MaxVolumes*
+
Setzen Sie diesen Wert auf 256.

* *NFS.MaxQueueDepth*
+
Setzen Sie diesen Wert auf 128 oder höher, um Engpässe in der Warteschlange zu vermeiden.

* *NFS.HeartbeatMaxFailures*
+
Setzen Sie diesen Wert für alle NFS-Konfigurationen auf 10.

* *NFS.HeartbeatFrequency*
+
Setzen Sie diesen Wert für alle NFS-Konfigurationen auf 12.

* *NFS.HeartbeatTimeout*
+
Setzen Sie diesen Wert für alle NFS-Konfigurationen auf 5.





== FC-/FCoE-Einstellungen

* *Pfadauswahl-Richtlinie*
+
Setzen Sie diesen Wert auf „`RR`“ (Round Robin), wenn FC-Pfade mit ALUA verwendet werden.

+
Setzen Sie diesen Wert für alle anderen Konfigurationen auf „`FIXED`“.

+
Wenn Sie diesen Wert auf „`RR`“ setzen, ist für den Lastausgleich über alle aktiven/optimierten Pfade hinweg hilfreich. Der Wert „`FIXED`“ wird für ältere Konfigurationen ohne ALUA verwendet und verhindert Proxy-I/O

* *Disk.QFullSampleSize*
+
Setzen Sie diesen Wert für alle Konfigurationen auf 32. Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert.

* *Disk.QFullThreshold*
+
Setzen Sie diesen Wert für alle Konfigurationen auf 8. Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert.

* * Emulex FC HBA-Timeouts*
+
Standardwert verwenden.

* *QLogic FC HBA Timeouts*
+
Standardwert verwenden.





== ISCSI-Einstellungen

* *Pfadauswahl-Richtlinie*
+
Setzen Sie diesen Wert für alle iSCSI-Pfade auf „`RR`“.

+
Wenn Sie diesen Wert auf „`RR`“ setzen, ist für den Lastausgleich über alle aktiven/optimierten Pfade hinweg hilfreich.

* *Disk.QFullSampleSize*
+
Setzen Sie diesen Wert für alle Konfigurationen auf 32. Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert.

* *Disk.QFullThreshold*
+
Setzen Sie diesen Wert für alle Konfigurationen auf 8. Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert.


