---
permalink: configure/task_discover_storage_systems_and_hosts.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie ONTAP-Tools zum ersten Mal in einem vSphere Client ausführen, erkennt ONTAP-Tools die ESXi-Hosts, ihre LUNs und NFS-Exporte und die NetApp Storage-Systeme, die Eigentümer dieser LUNs und Exporte sind. 
---
= Erkennen von Storage-Systemen und Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP-Tools zum ersten Mal in einem vSphere Client ausführen, erkennt ONTAP-Tools die ESXi-Hosts, ihre LUNs und NFS-Exporte und die NetApp Storage-Systeme, die Eigentümer dieser LUNs und Exporte sind.

*Was Sie brauchen*

* Alle ESXi-Hosts müssen eingeschaltet und verbunden sein.
* Alle zu ermittelenden Storage Virtual Machines (SVMs) müssen ausgeführt werden. Jeder Cluster-Node muss für das verwendete Storage-Protokoll (NFS, iSCSI, FC oder NVMe/FC) mindestens eine Daten-LIF konfiguriert sein.


*Über diese Aufgabe*

Sie können jederzeit neue Storage-Systeme ermitteln oder Informationen zu vorhandenen Storage-Systemen aktualisieren, um die aktuellsten Kapazitäts- und Konfigurationsinformationen zu erhalten. Sie können auch die Anmeldeinformationen ändern, die die ONTAP Tools zur Anmeldung bei den Storage-Systemen verwenden.

Bei der Erkennung der Speichersysteme erfasst ONTAP-Tools Informationen von den ESXi-Hosts, die von der vCenter Server-Instanz gemanagt werden.

*Schritte*

. Wählen Sie auf der vSphere Client-Startseite die Option *Hosts und Cluster* aus.
. Klicken Sie mit der rechten Maustaste auf das erforderliche Rechenzentrum, und wählen Sie dann *NetApp ONTAP Tools* > *Update Host- und Speicherdaten* .
+
Das ONTAP-Tool zeigt ein Dialogfeld „Bestätigen“ an, in dem Sie darüber informiert werden, dass durch diese Aktion die Erkennung aller verbundenen Speichersysteme neu gestartet wird und einige Minuten in Anspruch nehmen kann. Möchten Sie fortfahren?

. Klicken Sie auf *JA*.
. Wählen Sie die erkannten Speicher-Controller aus, die den Status aufweisen `Authentication Failure`, Und klicken Sie dann auf *AKTIONEN* > *Ändern*.
. Geben Sie die erforderlichen Informationen in das Dialogfeld * Speichersystem ändern* ein.
. Wiederholen Sie die Schritte 4 und 5 für alle Speicher-Controller mit `Authentication Failure` Status:


Nach Abschluss des Erkennungsvorgangs führen Sie folgende Schritte aus:

* Verwenden Sie ONTAP-Tools, um ESXi-Hosteinstellungen für Hosts zu konfigurieren, die das Warnsymbol in der Spalte Adaptereinstellungen, in der Spalte MPIO-Einstellungen oder in der Spalte NFS-Einstellungen anzeigen.
* Geben Sie die Anmeldeinformationen des Speichersystems an.

