---
permalink: configure/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: Mit ONTAP® Tools für VMware vSphere können Sie Standardanmeldeinformationen für ein Speichersystem in Ihrem vCenter Server festlegen. 
---
= Legen Sie die Standardanmeldeinformationen für Speichersysteme fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den ONTAP Tools für VMware vSphere können Sie Standardanmeldeinformationen für ein Speichersystem in Ihrem vCenter Server festlegen.

*Was Sie brauchen*

Sie müssen den vCenter Server ausgewählt haben, den Sie zum Erstellen von Standardanmeldeinformationen verwenden möchten.

*Über diese Aufgabe*

Wenn Sie Standardanmeldedaten für Storage-Systeme einrichten, verwendet die Virtual Storage Console (VSC) diese Anmeldedaten für die Anmeldung bei einem Storage-System, das die VSC gerade erkannt hat. Wenn die Standardanmeldeinformationen nicht funktionieren, müssen Sie sich manuell beim Speichersystem anmelden. VSC und SRA unterstützen das Hinzufügen von Anmeldeinformationen des Storage-Systems auf Cluster-Ebene oder SVM-Ebene. Vasa Provider kann aber nur mit Anmeldedaten auf Cluster-Ebene arbeiten.

*Schritte*

. Klicken Sie auf der Startseite der ONTAP-Tools auf *Einstellungen* > *Administratoreinstellungen* > *Standardanmeldeinformationen für das Speichersystem konfigurieren*.
. Geben Sie im Dialogfeld Standardanmeldeinformationen des Speichersystems den Benutzernamen und das Kennwort für das Speichersystem ein.
+
Storage Controller-Anmeldedaten werden in ONTAP basierend auf dem Benutzernamen und dem Passwort-Paar zugewiesen. Die Zugangsdaten für den Storage Controller können entweder das Administratorkonto oder ein benutzerdefiniertes Konto, das die rollenbasierte Zugriffssteuerung verwendet.

+
Sie können die Rollen, die dem Benutzernamen und Passwort des Storage Controllers zugeordnet sind, nicht mit VSC ändern. Um eine neue ONTAP-Benutzerrolle für die Verwendung mit ONTAP Tools zu ändern oder zu erstellen, können Sie System Manager verwenden.

+
Weitere Informationen finden Sie im Abschnitt „`Konfigurieren von Benutzerrollen und -Berechtigungen`“.

. Klicken Sie auf *OK*, um die Standardanmeldeinformationen zu speichern.


Wenn Sie die Anmeldedaten des Speichersystems aktualisiert haben, weil ein Speichersystem den Status „`Authentifizierungsfehler`“ gemeldet hat, klicken Sie auf die Option *ALLE WIEDERERKENNEN*, die auf der Seite Speichersysteme verfügbar ist. Ist dies der Fall, versucht die VSC mithilfe der neuen Zugangsdaten, sich mit dem Storage-System zu verbinden.
