---
permalink: configure/task_discover_storage_systems_and_hosts.html 
sidebar: sidebar 
keywords:  
summary: 'Wenn Sie zum ersten Mal Virtual Storage Console \ (VSC\) in einem vSphere Client ausführen, erkennt VSC die ESXi Hosts, ihre LUNs und NFS Exporte sowie die NetApp Storage-Systeme, die über diese LUNs und Exporte verfügen.' 
---
= Erkennen von Storage-Systemen und Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie zum ersten Mal Virtual Storage Console (VSC) in einem vSphere Client ausführen, erkennt VSC die ESXi Hosts, ihre LUNs und NFS Exporte sowie die NetApp Storage-Systeme, die im Besitz dieser LUNs und Exporte sind.

*Was Sie brauchen*

* Alle ESXi-Hosts müssen eingeschaltet und verbunden sein.
* Alle zu ermittelenden Storage Virtual Machines (SVMs) müssen ausgeführt werden. Jeder Cluster-Node muss für das verwendete Storage-Protokoll (NFS, iSCSI, FC oder NVMe/FC) mindestens eine Daten-LIF konfiguriert sein.


*Über diese Aufgabe*

Sie können jederzeit neue Storage-Systeme ermitteln oder Informationen zu vorhandenen Storage-Systemen aktualisieren, um die aktuellsten Kapazitäts- und Konfigurationsinformationen zu erhalten. Sie können auch die Zugangsdaten, die VSC zur Anmeldung bei den Storage-Systemen verwendet, ändern.

Bei der Erkennung der Storage-Systeme erfasst VSC Informationen von den ESXi Hosts, die von der vCenter Server Instanz gemanagt werden.

*Schritte*

. Wählen Sie auf der vSphere Client-Startseite die Option *Hosts und Cluster* aus.
. Klicken Sie mit der rechten Maustaste auf das erforderliche Rechenzentrum, und wählen Sie dann *NetApp ONTAP Tools* > *Update Host- und Speicherdaten* .
+
VSC zeigt ein Dialogfeld „Bestätigen“ an, in dem Sie darüber informiert werden, dass durch diese Aktion die Erkennung aller verbundenen Storage-Systeme neu gestartet wird und einige Minuten in Anspruch nehmen kann. Möchten Sie fortfahren?

. Klicken Sie auf *JA*.
. Wählen Sie die erkannten Speicher-Controller aus, die den Status aufweisen `Authentication Failure`, Und klicken Sie dann auf *AKTIONEN* > *Ändern*.
. Geben Sie die erforderlichen Informationen in das Dialogfeld * Speichersystem ändern* ein.
. Wiederholen Sie die Schritte 4 und 5 für alle Speicher-Controller mit `Authentication Failure` Status:


Nach Abschluss des Erkennungsvorgangs führen Sie folgende Schritte aus:

* Verwenden Sie VSC, um ESXi Host-Einstellungen für Hosts zu konfigurieren, die in der Spalte Adaptereinstellungen, in der Spalte MPIO-Einstellungen oder in der Spalte NFS-Einstellungen das Symbol Alert anzeigen.
* Geben Sie die Anmeldeinformationen des Speichersystems an.

