---
permalink: configure/task_add_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: Sie können ONTAP Tools Storage-Systeme manuell hinzufügen. 
---
= Storage-Systeme hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP Tools Storage-Systeme manuell hinzufügen.


NOTE: Wenn ONTAP Cluster SAML-aktiviert ist, erfolgt die Kommunikation mit ONTAP über eine Basisauthentifizierung.

*Über diese Aufgabe*

Jedes Mal, wenn Sie ONTAP-Tools starten oder die Option *NEU ENTDECKEN* auswählen, erkennt ONTAP-Tools für VMware vSphere automatisch die verfügbaren Speichersysteme.


NOTE: VVol Datastores werden auf SVM-Benutzern nicht unterstützt.

*Schritte*

. Sie können ONTAP Tools ein Storage-System hinzufügen, indem Sie eine der Optionen auf der Homepage der ONTAP Tools wählen:
+
** Klicken Sie Auf *Speichersysteme* > *Hinzufügen*. Oder
** Klicken Sie auf *Übersicht* > *erste Schritte* und dann auf die Schaltfläche *HINZUFÜGEN* unter Speichersystem hinzufügen.


. Geben Sie im Dialogfeld *Storage-System hinzufügen* die Management-IP-Adresse und die Anmeldeinformationen für dieses Speichersystem ein.
+
Wenn Sie ein Storage-System hinzufügen, sollte jede Kommunikation zwischen dem ONTAP Tools Plug-in und dem Storage-System gegenseitig authentifiziert werden.

+
Sie können auch Storage-Systeme mit der IPv6-Adresse des Clusters oder der SVM hinzufügen.

+
Wenn Sie Speicher auf der Seite ONTAP Tools Storage System hinzufügen, geben Sie die vCenter Server-Instanz an, in der sich der Speicher befindet. Das Dialogfeld Add Storage System enthält eine Dropdown-Liste der verfügbaren vCenter Server-Instanzen. ONTAP-Tools zeigen diese Option nicht an, wenn Sie Speicher zu einem Rechenzentrum hinzufügen, das bereits mit einer vCenter Server-Instanz verknüpft ist.

+
HINWEIS:

+
** Ab der Version ONTAP Tools 9.12 erfolgt die Kommunikation der ONTAP Storage-Systeme durch zertifikatbasierte Authentifizierung.
** Die herkömmlichen Datastore-Aktionen wie Löschen, Ändern der Größe und Mounten sind nicht zulässig, wenn eines der Client- oder Cluster-Zertifikate ungültig ist.
** Die vVol Datastore-Aktionen wie „Speicher erweitern“, „Datastore mounten“ sind nicht zulässig, wenn eines der Client- oder Clusterzertifikate ungültig ist.
** Aktionen wie Löschen, Speicher entfernen und Eigenschaften bearbeiten sind zulässig, da für diese Aktionen keine ONTAP-Kommunikation erforderlich ist.
** Um ein Storage-System mit dem im SVM-Umfang enthaltenen Benutzer hinzuzufügen, muss der Storage-System-Cluster-Administrator den Benutzer bearbeiten und die Authentifizierungsmethode *Certificate* zu den Applikationen HTTP und ONTAPI hinzufügen.
+
In den erweiterten Optionen gibt es zwei Möglichkeiten, das *ONTAP-Cluster-Zertifikat* hochzuladen:

+
... *Automatisch abrufen* - ruft die Zertifikate automatisch ab.
... *Manuelles Hochladen* - Sie müssen manuell zu dem Ort navigieren, wo sich das Zertifikat befindet und das Zertifikat hochladen.




. Klicken Sie auf *OK*, nachdem Sie alle erforderlichen Informationen hinzugefügt haben.
+
Das Popup-Fenster „Clusterzertifikat autorisieren“ wird angezeigt.

. Klicken Sie auf *Zertifikat anzeigen*, um die Zertifikatdetails anzuzeigen. Klicken Sie auf *Ja*, um das Speichersystem hinzuzufügen

