---
permalink: configure/task_register_oncommand_api_services_with_ontap_tools.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: 'Bei Verwendung von ONTAP 9.6 oder einer älteren Version können Sie über das VVols-Dashboard nur die Details zu VMware Virtual Volumes \ (VVols\) Datastores und Virtual Machines anzeigen, wenn Sie über OnCommand API Services für VASA Provider verfügen, um Daten für die VVols-VM- und Datastore-Berichte abzurufen.' 
---
= Registrieren Sie die OnCommand API-Services mit ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei Verwendung von ONTAP 9.6 oder einer älteren Version können Sie über das VVols Dashboard nur Details zu VMware Virtual Volumes (VVols) Datastores und Virtual Machines anzeigen, wenn Sie OnCommand API Services für VASA Provider registriert haben, um Daten für die VVols-VM- und Datastore-Berichte abzurufen.

*Was Sie brauchen*

Sie müssen OnCommand API Services 2.1 oder höher von der NetApp Support-Website heruntergeladen haben.


NOTE: Im VVols Dashboard werden die Performance-Kennzahlen nur angezeigt, wenn SAN VVols Datastores und Virtual Machines mit ONTAP 9.3 oder höher konfiguriert werden.

*Schritte*

. Klicken Sie auf der Startseite von ONTAP Tools auf *Einstellungen*.
. Klicken Sie auf der Registerkarte Verwaltungseinstellungen auf *Erweiterung verwalten*.
. Verwenden Sie den Schieberegler „OnCommand-API-Dienste registrieren“, um OnCommand-API-Dienste zu aktivieren.
. Geben Sie die IP-Adresse, den Service-Port und die Anmeldeinformationen für OnCommand-API-Dienste ein.
+
Sie können auch das Dialogfeld „VASA Provider-Erweiterungen managen“ für die folgenden Änderungen verwenden:

+
** So aktualisieren Sie die Registrierung für OnCommand-API-Dienste, wenn Änderungen an den Anmeldedaten vorgenommen werden.
** So können Sie OnCommand API Services wieder aufheben, wenn Sie das VVols Dashboard nicht mehr benötigen.
+
Um die OnCommand API Services-Registrierung für VASA Provider zu entfernen, müssen Sie das Kontrollkästchen OnCommand API Services registrieren deaktivieren.



. Klicken Sie Auf *Anwenden*.
+
Im VVols Dashboard werden die Kennzahlen für ONTAP 9.6 oder frühere SAN VVols-Datastores nur angezeigt, wenn die Registrierung der OnCommand API Services abgeschlossen ist.



*Verwandte Informationen*

https://mysupport.netapp.com/site/global/dashboard["NetApp Support"]
