---
permalink: configure/task_provision_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: Sie können mit dem Assistenten für Provisioner-Datenspeicher nur dann einen VVols-Datastore bereitstellen, wenn VASA Provider in den ONTAP Tools aktiviert ist. 
---
= Bereitstellung von VVols Datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mit dem Assistenten für Provisioner-Datenspeicher nur dann einen VVols-Datastore bereitstellen, wenn VASA Provider in den ONTAP Tools aktiviert ist.

*Was Sie brauchen*

* Sie sollten sicherstellen, dass die Subnetzdetails aller Netzwerke, mit denen der ESXi-gehostete verbunden ist, in der Kaminoprefs.XML eingegeben werden.
+
Siehe *Aktivieren der Datastore-Montage über verschiedene Subnetze* Abschnitt.

* Sie sollten eine ähnliche Replizierungsrichtlinie konfigurieren und für die Datastores am Quell- und Zielspeicherort planen, damit die umgekehrte Replizierung erfolgreich durchgeführt werden kann.


Das Menü „Datastore bereitstellen“ ermöglicht die Angabe eines Storage-Funktionsprofils für den Datastore. Dadurch können konsistente Service Level Objectives (SLOs) angegeben und der Bereitstellungsprozess vereinfacht werden. Sie können nur ein Storage-Funktionsprofil angeben, wenn Sie VASA Provider aktiviert haben.

FlexVol Volumes, die als Storage-Unterstützung verwendet werden, werden auf dem VVols Dashboard nur angezeigt, wenn sie ONTAP 9.5 oder höher ausführen. Sie sollten den vCenter Server New Datastore Wizard zur Bereitstellung von VVols Datastores nicht verwenden.

* Zum Erstellen von VVols-Datastores müssen Sie die Cluster-Anmeldedaten verwenden.
+
Sie können SVM-Anmeldedaten nicht zum Erstellen von VVols-Datastores verwenden.

* VASA Provider unterstützt nicht das Klonen einer Virtual Machine, die sich auf dem VVols Datastore eines Protokolls für einen anderen Datastore mit einem anderen Protokoll befindet.
* Sie sollten die Paarung des Clusters und die SVM-Kopplung am Quell- und Zielstandort abgeschlossen haben.


*Über diese Aufgabe*


NOTE: Die Version 9.10 von ONTAP Tools unterstützt das Erstellen von VVols-Datastores mit einer VMDK-Größe von mehr als 16 TB für All-SAN-Array (ASA)-Storage-Plattformen vom Typ ONTAP 9.9.1 oder höher.

*Schritte*

. Klicken Sie auf der vSphere Client-Startseite auf *Hosts und Cluster*.
. Wählen Sie im Navigationsbereich das Rechenzentrum aus, auf dem Sie den Datastore bereitstellen möchten.
. Geben Sie die Hosts an, auf denen der Datastore gemountet werden soll.
+
|===


| *Um den Datenspeicher zur Verfügung zu stellen...* | *Do this...* 


 a| 
Alle Hosts in einem Datacenter
 a| 
Klicken Sie mit der rechten Maustaste auf ein Datacenter und wählen Sie dann *NetApp ONTAP-Tools* > *Datastore bereitstellen* aus.



 a| 
Alle Hosts in einem Cluster
 a| 
Klicken Sie mit der rechten Maustaste auf einen Cluster und wählen Sie dann *NetApp ONTAP Tools* > *Datenspeicher bereitstellen* aus.



 a| 
Einem einzelnen Host aus
 a| 
Klicken Sie mit der rechten Maustaste auf einen Host, und wählen Sie dann *NetApp ONTAP Tools* > *Datenspeicher bereitstellen* aus.

|===
. Füllen Sie die Felder im Dialogfeld Neuer Datenspeicher aus, um den Datenspeicher zu erstellen.
+
Die meisten Felder im Dialogfeld sind selbsterklärend. In der folgenden Tabelle werden einige der Felder beschrieben, für die Sie möglicherweise eine Anleitung benötigen.

+
|===


| *Abschnitt* | *Beschreibung* 


 a| 
Allgemein
 a| 
Im Abschnitt „Allgemein“ des Dialogfelds „Neuer Datenspeicher“ können Sie den Speicherort, den Namen, die Beschreibung, den Typ und das Protokoll für den neuen Datenspeicher eingeben. Der VVols-Datastore-Typ wird zur Konfiguration eines VVols-Datastores verwendet.

Sie können den VVols Datastore bereitstellen, wenn die VASA Provider-Funktion aktiviert ist. Siehe, link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Aktivieren Sie VASA Provider zur Konfiguration von virtuellen Datastores"] Entsprechende Details. Der VVols Datastore unterstützt NFS-, iSCSI-, FC/FEoE- und NVMe/FC-Protokolle.


NOTE: Das NVMe/FC-Protokoll für VVols Datastore ist verfügbar, wenn ONTAP Tools für vCenter 8.0 und höher registriert sind und wenn die ONTAP-Version ONTAP 9.91P3 oder höher lautet.


NOTE: Wenn Sie iSCSI VVols-Datastore für die VVols-Replizierung bereitstellen, müssen Sie vor der Erstellung des VVols-Datastores am Zielstandort SnapMirror Update und Cluster-Neuerkennung durchführen.



 a| 
Storage-System
 a| 
In diesem Abschnitt können Sie auswählen, ob die Replizierung im VVols-Datastore aktiviert oder deaktiviert werden soll. Für diesen Release ist nur ein Replizierungsprofil vom asynchronen Typ zulässig. Anschließend können Sie ein oder mehrere Storage-Funktionsprofile auswählen. Die vom System empfohlenen Werte von gepaarten *Storage System* und *Storage VM* werden automatisch ausgefüllt. Die empfohlenen Werte werden nur dann ausgefüllt, wenn sie in ONTAP gekoppelt sind. Sie können diese Werte bei Bedarf ändern.

*Hinweis:* beim Erstellen von FlexVol Volumes in ONTAP sollten Sie darauf achten, diese mit den Attributen zu erstellen, die Sie im Storage-Funktionsprofil auswählen möchten. Sowohl Lese-Schreib- als auch Datenschutz FlexVol-Volumes sollten ähnliche Attribute aufweisen.

Nachdem FlexVol Volumes erstellt und SnapMirror in ONTAP initialisiert wurde, sollten Sie eine Speicherwiedererkennung in den ONTAP-Tools ausführen, um die neuen Volumes sehen zu können.



 a| 
Storage-Attribute
 a| 
Sie sollten den Zeitplan für SnapMirror und das erforderliche FlexVol Volume aus der vorhandenen Liste auswählen. Dieser Zeitplan sollte dem Zeitplan ähneln, der auf der Seite VM Storage Policies ausgewählt wurde. Der Benutzer sollte FlexVol Volumes auf ONTAP mit SnapMirror erstellt haben, die aufgeführt sind. Sie können das Standard-Storage-Funktionsprofil auswählen, das für die Erstellung von VVols verwendet werden soll. Verwenden Sie dazu die Option *Default Storage Capability Profile*. Standardmäßig sind alle Volumes auf maximale Autogrow-Größe auf 120 % gesetzt und Standard-Snapshots sind auf diesen Volumes aktiviert.

*Hinweis:*

** Ein FlexVol Volume, das Teil eines VVols-Datastores ist, kann nicht unter die vorhandene Größe schrumpfen. Dieses Volume kann jedoch maximal 120 % wachsen. Standard-Snapshots sind auf diesem FlexVol Volume aktiviert.
** Die minimale Größe der FlexVol-Volumen, die Sie erstellen sollten, ist 5GB.


|===
. Klicken Sie im Abschnitt Zusammenfassung auf *Fertig stellen*.


*Ergebnis*

Bei der Konfiguration eines VVols-Datastores wird im Back-End eine Replizierungsgruppe erstellt.

*Verwandte Informationen*

link:../manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html["Analyse der Performance-Daten mithilfe des VVols Dashboards"]
