---
permalink: configure/task_discover_storage_systems_and_hosts.html 
sidebar: sidebar 
keywords:  
summary: 'Wenn Sie zum ersten Mal Virtual Storage Console \ (VSC\) in einem vSphere Client ausführen, erkennt VSC die ESXi Hosts, ihre LUNs und NFS Exporte sowie die NetApp Storage-Systeme, die über diese LUNs und Exporte verfügen.' 
---
= Erkennen von Storage-Systemen und Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie zum ersten Mal Virtual Storage Console (VSC) in einem vSphere Client ausführen, erkennt VSC die ESXi Hosts, ihre LUNs und NFS Exporte sowie die NetApp Storage-Systeme, die im Besitz dieser LUNs und Exporte sind.

*Was Sie brauchen*

* Alle ESXi-Hosts müssen eingeschaltet und verbunden sein.
* Alle zu entdeckenden Storage Virtual Machines (SVMs) müssen ausgeführt werden. Jeder Cluster Node muss über mindestens eine Daten-LIF verfügen, die für das verwendete Storage-Protokoll (NFS, iSCSI oder FC) konfiguriert ist.


*Über diese Aufgabe*

Sie können jederzeit neue Storage-Systeme ermitteln oder Informationen zu vorhandenen Storage-Systemen aktualisieren, um die aktuellsten Kapazitäts- und Konfigurationsinformationen zu erhalten. Sie können auch die Zugangsdaten, die VSC zur Anmeldung bei den Storage-Systemen verwendet, ändern.

Bei der Erkennung der Storage-Systeme erfasst VSC Informationen von den ESXi Hosts, die von der vCenter Server Instanz gemanagt werden.

*Schritte*

. Wählen Sie auf der vSphere Client-Startseite die Option *Hosts und Cluster* aus.
. Klicken Sie mit der rechten Maustaste auf das gewünschte Datacenter und wählen Sie dann *NetApp VSC* > *Host aktualisieren und Speicherdaten* aus.
+
Die VSC zeigt ein Dialogfeld „Bestätigen“ an, in dem Sie darauf hingewiesen werden, dass dieser Vorgang viel Zeit in Anspruch nehmen kann.

. Klicken Sie auf *OK*.
. Wählen Sie die erkannten Speichercontroller mit dem Status „`Authentifizierungsfehler`“ aus und klicken Sie dann auf *AKTIONEN* > *Ändern*.
. Geben Sie die erforderlichen Informationen im Dialogfeld Speichersystem ändern ein.
. Wiederholen Sie die Schritte 4 und 5 für alle Speichercontroller mit dem Status „`Authentication Failure`“.


Nach Abschluss des Erkennungsvorgangs führen Sie folgende Schritte aus:

* Verwenden Sie VSC, um ESXi Host-Einstellungen für Hosts zu konfigurieren, die in der Spalte Adaptereinstellungen, in der Spalte MPIO-Einstellungen oder in der Spalte NFS-Einstellungen das Symbol Alert anzeigen.
* Geben Sie die Anmeldeinformationen des Speichersystems an.

