---
permalink: manage/concept_datastore_reports.html 
sidebar: sidebar 
keywords: Datastore Reports 
summary: Die Datastore-Berichte bieten detaillierte Informationen zu herkömmlichen Datastores und den auf diesen Datastores erstellten Virtual Machines. 
---
= Datastore Reports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Datastore-Berichte bieten detaillierte Informationen zu herkömmlichen Datastores und den auf diesen Datastores erstellten Virtual Machines.

Das herkömmliche Dashboard ermöglicht es Ihnen, potenzielle Probleme mit den Datastores und Virtual Machines in Ihrem vCenter Server zu prüfen und zu identifizieren. Sie können Berichte anzeigen, sortieren und exportieren. Die Daten für die Berichte zu herkömmlichen Datastores und Virtual Machines werden vom vCenter Server bereitgestellt. Doch aufgrund der Unterstützung von FlexGroup-gestützten Datastore kommen einige Metriken wie Latenz, Durchsatz und IOPS bei ONTAP zum Einsatz.


NOTE: FlexGroup Datastores, die auf Virtual Machines (SVMs) als direkte Storage-Lösung konfiguriert sind, werden nicht von der Dateiüberwachung unterstützt.

Der Datastore bietet die folgenden vordefinierten Berichte:

* Datastore Report
* Virtual Machine Report


* Datastore-Bericht*

+ das Menü Datastore Report bietet Informationen zu den folgenden Parametern für Datenspeicher:

* Name des Datenspeichers
* Datenspeichertyp: NFS oder VMFS
* Volume-Stil
+
Der Volume-Stil kann entweder ein FlexVol Volume oder ein FlexGroup Volume sein.

* Freier Speicherplatz
* Genutzter Speicherplatz
* Gesamter Speicherplatz
* Prozentsatz des genutzten Speicherplatzes
* Prozentsatz des verfügbaren Speicherplatzes
* IOPS
+
Der Bericht zeigt die IOPS für den Datastore an.

* Latenz
+
Der Bericht zeigt die Latenzinformationen für den Datastore an.

+
Sie können auch die Zeit überprüfen, zu der der Bericht generiert wurde. Das Menü Datastore Report ermöglicht es Ihnen, den Bericht nach Ihren Anforderungen zu organisieren und dann den organisierten Bericht mit der Schaltfläche *Export in CSV* zu exportieren. Bei den Datenspeichernamen im Bericht handelt es sich um Links, die zur Registerkarte Überwachung des ausgewählten Datastores navigieren. Dort können Sie die Performance-Metriken des Datastores anzeigen.



*Virtual Machine Report*

+ das Menü „Virtual Machine Report“ enthält die Performance-Kennzahlen für alle Virtual Machines, die von VSC bereitgestellte Datenspeicher für einen ausgewählten vCenter Server verwenden. Die in den Virtual Machine Reports angezeigten Kennzahlen sind Archivdaten, die alle 30 Minuten für Virtual Machines in herkömmlichen Datastores erfasst werden. Die „`Letzte Aktualisierungszeit`“ und „`Nächste Aktualisierungszeit `“ werden in die Tabelle aufgenommen, um Einzelheiten darüber zu geben, wann die Daten erfasst wurden und wann die nächste Datenerfassung erfolgt.

* Name der virtuellen Maschine
* Name des Datenspeichers
* Volume-Stil
+
Der Volume-Stil kann entweder ein FlexVol Volume oder ein FlexGroup Volume sein.

* Quelle
+
Als Quelle für die Details der Virtual Machine kann es sich um ONTAP oder vCenter Server handeln.

* Latenz
+
Der Bericht zeigt die Latenz für Virtual Machines in allen Datastores an, die den Virtual Machines zugeordnet sind.

* IOPS
* Durchsatz
* Engagierte Kapazität
+
Der Bericht zeigt den Wert für die für eine virtuelle Maschine bestimmte Kapazität an.

* Host
+
Der Bericht zeigt die Hostsysteme an, auf denen die virtuelle Maschine verfügbar ist.

* Verfügbarkeit
+
Der Bericht zeigt die Zeit an, zu der die virtuelle Maschine eingeschaltet ist und auf einem ESXi-Host verfügbar ist.

* Stromzustand
+
Der Bericht zeigt an, ob die virtuelle Maschine eingeschaltet oder ausgeschaltet ist.



Jeder Name der virtuellen Maschine im Bericht ist ein Link zur Registerkarte Überwachung der ausgewählten virtuellen Maschine. Sie können den Bericht virtueller Maschinen nach Ihren Anforderungen sortieren und den Bericht in einer CSV-Datei exportieren und den Bericht auf Ihrem lokalen System speichern. Der Zeitstempel des Berichts wird ebenfalls an den gespeicherten Bericht angehängt.

Bei Virtual Machines, die durch FlexGroup Volumes gesichert werden, werden Dateien für das Monitoring auf ONTAP registriert, wenn eine neue Virtual Machine eingeschaltet ist. Die historischen Metriken für Latenz, Durchsatz und IOPS erhalten, wenn auf VM-Berichte von ONTAP zugegriffen wird.
