---
permalink: manage/reference_verify_vvols_dashboard_data_requirements.html 
sidebar: sidebar 
keywords: vVol dashboard 
summary: 'Sie müssen einige wichtige Anforderungen des VVols Dashboards überprüfen, um dynamische Details zu VMware Virtual Volumes \(VVols\)-Datastores und Virtual Machines anzuzeigen.' 
---
= Datenanforderungen für das VVols Dashboard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen einige wichtige Anforderungen des VVols Dashboards überprüfen, um dynamische Details zu VMware Virtual Volumes (VVols) Datastores und Virtual Machines anzuzeigen.

Die folgende Tabelle gibt einen Überblick darüber, was Sie überprüfen sollten, ob das VVols Dashboard nicht die Performance-Metriken für die bereitgestellten SAN VVols Datastores und Virtual Machines anzeigt.

|===


| *Überlegungen* | *Beschreibung* 


 a| 
Erstmalige Implementierung von OnCommand API Services
 a| 
* Wenn Sie ONTAP Cluster 9.6 oder früher haben, dann verwenden Sie OnCommand API Services 2.1 oder höher.
+
Sie müssen bei VASA Provider keine Registrierung von OnCommand API Services durchführen, wenn Sie ONTAP 9.7 oder höher verwenden.

* Nach dem Herunterladen und Installieren der OnCommand API Services von der NetApp Support-Website müssen Sie die Installationsanweisungen befolgen, die Sie im Installations- und Setup-Leitfaden „ _OnCommand API Services Installation and Setup_“ erhalten haben.
* Jede VASA Provider-Instanz muss über eine dedizierte OnCommand API Services Instanz verfügen.
+
OnCommand API Services dürfen nicht zwischen mehreren VASA Provider-Instanzen oder vCenter Servern gemeinsam genutzt werden.

* OnCommand API Services wird ausgeführt und ist zugänglich.




 a| 
Storage-System
 a| 
* Sie verwenden ONTAP 9.3 oder höher.
* Sie verwenden die entsprechenden Anmeldedaten für das Speichersystem.
* Das Storage-System ist aktiv und kann aufgerufen werden.
* Die ausgewählte virtuelle Maschine muss mindestens einen VVols-Datastore verwenden, und I/O-Vorgänge werden auf der Festplatte der virtuellen Maschine ausgeführt.


|===