---
permalink: manage/task_collect_the_log_files.html 
sidebar: sidebar 
keywords:  
summary: 'Sie können Protokolldateien für ONTAP®-Tools für VMware vSphere über die in der grafischen Benutzeroberfläche der ONTAP-Tools \(GUI\) verfügbare Option sammeln. Der technische Support fordert Sie möglicherweise auf, die Protokolldateien zu sammeln, damit Sie Probleme beheben können.' 
---
= Sammeln Sie die Protokolldateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Protokolldateien für ONTAP Tools für VMware vSphere über die in der grafischen Benutzeroberfläche (GUI) der ONTAP Tools verfügbare Option sammeln. Der technische Support fordert Sie möglicherweise auf, die Protokolldateien zu sammeln, damit Sie Probleme beheben können.

*Über diese Aufgabe*

Wenn Sie VASA Provider-Protokolldateien benötigen, können Sie über das Bedienfeld des Anbieters ein Supportpaket generieren. Diese Seite ist Teil der VASA Provider-Wartungsmenüs, auf die Sie über die Konsole der virtuellen Appliance zugreifen können.

`\https://vm_ip:9083`

Sie können die ONTAP-Tools für VMware vSphere-Protokolldateien mithilfe der Funktion „`ONTAP-Tools für VMware vSphere-Protokolle exportieren`“ in der GUI der ONTAP-Tools sammeln. Wenn Sie ein Paket aus ONTAP Tools für VMware vSphere Log mit aktiviertem VASA Provider sammeln, werden die VP-Protokolle auch in den ONTAP Tools für das Paket VMware vSphere Log enthalten sein. Im Folgenden erfahren Sie, wie Sie die ONTAP-Tools für VMware vSphere-Protokolldateien erfassen:

*Schritte*

. Klicken Sie auf der Startseite der ONTAP-Tools auf *Konfiguration* > *ONTAP-Tools für VMware vSphere-Protokolle exportieren*.
+
Dieser Vorgang kann mehrere Minuten dauern.

. Speichern Sie die Datei auf Ihrem lokalen Computer, wenn Sie dazu aufgefordert werden.
+
Anschließend können Sie die Datei _.zip_ an den technischen Support senden.


