---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html 
sidebar: sidebar 
keywords:  
summary: 'Sie können die Performance überwachen und die fünf wichtigsten SAN- und NAS-Datastores von VMware Virtual Volumes \(VVols\) im vCenter Server anzeigen. Die Parameter basieren auf der VVols Konsole der ONTAP Tools, die Sie auswählen.' 
---
= Analyse der Performance-Daten mithilfe des VVols Dashboards
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Performance überwachen und die fünf wichtigsten SAN- und NAS-Datastores von VMware Virtual Volumes (VVols) im vCenter Server basierend auf den Parametern anzeigen, die Sie mithilfe des VVols Dashboards der ONTAP Tools auswählen.

*Was Sie brauchen*

* Sie sollten ONTAP 9.7 oder höher für Ihr Storage-System verwenden.


Die IOPS-Daten von ONTAP werden abgerundet und auf dem VVols Dashboard angezeigt. Es kann zwischen dem tatsächlichen IOPS-Wert, der von ONTAP bereitgestellt wird, und dem IOPS-Wert im VVols Dashboard Unterschiede geben. ONTAP Tools ermöglichen Performance-Monitoring für NFS-basierte VVols-Datastores.

* Die VVols Dashboard-Daten werden regelmäßig in einem Intervall von 10 Minuten aktualisiert.
* Wenn Sie ein Storage-System über Ihre vCenter Server Instanz hinzugefügt, geändert oder gelöscht haben, werden diese möglicherweise bereits seit einiger Zeit nicht mehr geändert.
* Der im Portlet „Übersicht“ des VVols Dashboards angezeigte Wert für IOPS-Gesamtkosten ist kein kumulativer Wert des Werts für Lese-IOPS und Schreib-IOPS.
* NFS-basierte Daten, die auf ONTAP 9.8 und höher bereitgestellt werden, werden automatisch für das Performance-Monitoring im VVols Dashboard registriert.


*Schritte*

. Klicken Sie auf der Startseite des vSphere Clients auf *ONTAP Tools*.
. Wählen Sie den erforderlichen vCenter-Server mit dem Selektor *INSTANCE* aus, um die Datastores anzuzeigen.
. Klicken Sie auf *Übersicht > VVols-Dashboard*.
+
Das Portlet „Datastores“ enthält folgende Details:

+
** Die Anzahl der VVols-Datastores, die über VASA Provider in der vCenter Server Instanz gemanagt werden
** Die fünf wichtigsten VVols-Datastores basierend auf Ressourcenauslastung und Performance-Parametern. Sie können die Liste der Datastores basierend auf dem genutzten Speicherplatz, der IOPS oder der Latenz und in der erforderlichen Reihenfolge ändern.


. Zeigen Sie die Details der Virtual Machines im Portlet „Virtual Machines“ an.
+
Das Portlet „Virtuelle Maschinen“ enthält folgende Details:

+
** Anzahl der Virtual Machines, die ONTAP Datastores in Ihrem vCenter Server verwenden
** Die fünf wichtigsten Virtual Machines basieren auf IOPS, Latenz, Durchsatz, engagierter Kapazität, Uptime Und logischer Speicherplatz, den Sie anpassen können, wie die fünf wichtigsten Virtual Machines im VVols Dashboard angezeigt werden.






== Datenanforderungen für das VVols Dashboard

Sie müssen einige wichtige Anforderungen des VVols Dashboards überprüfen, um dynamische Details zu VMware Virtual Volumes (VVols) Datastores und Virtual Machines anzuzeigen.

Die folgende Tabelle gibt einen Überblick darüber, was Sie überprüfen sollten, ob das VVols Dashboard nicht die Performance-Metriken für die bereitgestellten SAN VVols Datastores und Virtual Machines anzeigt.

|===
| *Überlegungen* | *Beschreibung* 


 a| 
Storage-System
 a| 
* Sie verwenden ONTAP 9.7 oder höher.
* Sie verwenden die entsprechenden Anmeldedaten für das Speichersystem.
* Das Storage-System ist aktiv und kann aufgerufen werden.
* Die ausgewählte virtuelle Maschine muss mindestens einen VVols-Datastore verwenden, und I/O-Vorgänge werden auf der Festplatte der virtuellen Maschine ausgeführt.


|===