---
permalink: manage/task_change_the_administrative_password.html 
sidebar: sidebar 
keywords:  
summary: Sie können das Administratorpasswort der ONTAP-Tools nach der Implementierung mit der Wartungskonsole ändern. 
---
= Ändern Sie das Administratorpasswort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Administratorpasswort der ONTAP-Tools nach der Implementierung mit der Wartungskonsole ändern. Passwort läuft nach 90 Tagen ab.

*Schritte*

. Öffnen Sie vom vCenter Server eine Konsole für die ONTAP Tools.
. Melden Sie sich als Wartungbenutzer an.
. Eingabe `1` Wählen Sie in der Wartungskonsole Anwendungskonfiguration aus.
. Eingabe `6` So wählen Sie *Administratorpasswort ändern* aus.
. Geben Sie ein Kennwort mit mindestens acht Zeichen und maximal 30 Zeichen ein. Das Passwort muss mindestens ein oberes, ein unteres, eine Ziffer und ein Sonderzeichen enthalten. Nach 75 Tagen nach dem Zurücksetzen des Passworts wird eine Warnung zum Ablauf des Kennworts angezeigt. Das neue Passwort darf nicht mit dem zuletzt verwendeten Passwort identisch sein.
+
Wenn Sie die Empfehlungen für das Passwort nicht befolgen, ist die Option für die Wartungskonsole auf das Ändern des Passworts beschränkt. Wenn das Passwort abgelaufen ist, werden Sie aufgefordert, das Passwort zu ändern.

. Eingabe `y` Im Bestätigungsdialogfeld.

