---
permalink: manage/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: Mit den ONTAP Tools für VMware vSphere können Sie Standardanmeldeinformationen für ein Speichersystem in Ihrem vCenter Server festlegen. 
---
= Legen Sie die Standardanmeldeinformationen für Speichersysteme fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den ONTAP Tools für VMware vSphere können Sie Standardanmeldeinformationen für ein Speichersystem in Ihrem vCenter Server festlegen.

*Was Sie brauchen*

Sie müssen den vCenter Server ausgewählt haben, den Sie zum Erstellen von Standardanmeldeinformationen verwenden möchten.

*Über diese Aufgabe*

Wenn Sie Standardanmeldeinformationen für Storage-Systeme einrichten, verwenden die ONTAP-Tools diese Anmeldeinformationen, um sich bei einem Storage-System anzumelden, das gerade von den ONTAP-Tools erkannt wurde. Wenn die Standardanmeldeinformationen nicht funktionieren, müssen Sie sich manuell beim Speichersystem anmelden. ONTAP-Tools und SRA unterstützen das Hinzufügen von Anmeldedaten für Storage-Systeme auf Cluster- oder SVM-Ebene. Vasa Provider kann aber nur mit Anmeldedaten auf Cluster-Ebene arbeiten.

*Schritte*

. Klicken Sie auf der Startseite der ONTAP-Tools auf *Einstellungen* > *Administratoreinstellungen* > *Standardanmeldeinformationen für das Speichersystem konfigurieren*.
. Geben Sie im Dialogfeld Standardanmeldeinformationen des Speichersystems den Benutzernamen und das Kennwort für das Speichersystem ein.
+
Storage Controller-Anmeldedaten werden in ONTAP basierend auf dem Benutzernamen und dem Passwort-Paar zugewiesen. Die Zugangsdaten für den Storage Controller können entweder das Administratorkonto oder ein benutzerdefiniertes Konto, das die rollenbasierte Zugriffssteuerung verwendet.

+
Sie können mit ONTAP Tools nicht die Rollen ändern, die mit dem Benutzernamen und dem Passwort-Paar des Storage Controllers verknüpft sind. Um eine neue ONTAP-Benutzerrolle für die Verwendung mit ONTAP Tools zu ändern oder zu erstellen, können Sie System Manager verwenden.

+
Siehe link:..configure/task_configure_user_role_and_privileges.html["Konfigurieren von Benutzerrollen und -Berechtigungen"]Abschnitt in der Dokumentation _ONTAP Tools for VMware vSphere_.

. Klicken Sie auf *OK*, um die Standardanmeldeinformationen zu speichern.


Wenn Sie die Anmeldedaten des Speichersystems aktualisiert haben, weil ein Speichersystem gemeldet hat `Authentication Failure` Status, sollten Sie auf die Option *REDISCOVER ALL* klicken, die auf der Seite Speichersysteme verfügbar ist. Dies ermöglicht es ONTAP Tools, mithilfe der neuen Zugangsdaten eine Verbindung zum Storage-System herzustellen.
